using System.IO.Pipes;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json.Nodes;
using Confectory.Core;
namespace Confectory.DesktopEntry;
public static class EntryProtocol
{
 public static string Canonical(string path)=>PackPaths.Resolve(path);
 public static string Key(string scope){scope=Path.GetFullPath(scope);if(OperatingSystem.IsWindows())scope=scope.ToUpperInvariant();return Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(scope+"\n"+Environment.UserName)));}
 public static string Folder(string scope)=>Path.Combine(Environment.GetEnvironmentVariable("CONFECTORY_ENTRY_STORAGE")??Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"Confectory","entry"),Key(scope));
 public static Manifest Read(string path){string ext=Path.GetExtension(path);if(!ext.Equals(".cproj",StringComparison.OrdinalIgnoreCase)&&!ext.Equals(".cpack",StringComparison.OrdinalIgnoreCase))throw new ArgumentException("Open a .cproj ProjectPack or .cpack pack; .cproject is not this format");if(new FileInfo(path).Length>1048576)throw new ArgumentException("Manifest exceeds 1MiB");var manifest=new Parser(File.ReadAllText(path),path).ParseManifest();if(ext.Equals(".cproj",StringComparison.OrdinalIgnoreCase)&&manifest.Kind!="project")throw new ArgumentException(".cproj must contain a ProjectPack declaration");return manifest;}
 public static JsonObject Inspect(string path,string target){path=Canonical(path);var manifest=Read(path);string platform=OperatingSystem.IsWindows()?"windows":OperatingSystem.IsLinux()?"linux":"unsupported";bool host=target=="portable"&&platform!="unsupported"||target==platform;bool declared=manifest.Targets.ContainsKey(target);return new(){["path"]=path,["kind"]=manifest.Kind,["namespace"]=manifest.Namespace,["canOpen"]=true,["standaloneDeclared"]=manifest.Standalone is null?null:JsonValue.Create(manifest.Standalone.Value),["supportsStandalone"]=manifest.SupportsStandalone,["entry"]=manifest.Entry,["targets"]=new JsonArray(manifest.Targets.Keys.Order(StringComparer.Ordinal).Select(x=>(JsonNode?)JsonValue.Create(x)).ToArray()),["currentHost"]=platform,["selectedTarget"]=target,["hostEligible"]=host,["targetDeclared"]=declared,["executionAssessment"]=manifest.Kind!="project"?"requires-project-composition":!manifest.SupportsStandalone?"standalone-disabled":manifest.Entry is null?"missing-entry":!declared?"target-not-declared":!host?"host-target-unavailable":"requires-explicit-build-and-runtime-verification"};}
 public static async Task Write(Stream stream,string json,CancellationToken cancel){var bytes=Encoding.UTF8.GetBytes(json);if(bytes.Length>16384)throw new ArgumentException("Entry message budget");var header=new byte[4];System.Buffers.Binary.BinaryPrimitives.WriteInt32LittleEndian(header,bytes.Length);await stream.WriteAsync(header,cancel);await stream.WriteAsync(bytes,cancel);await stream.FlushAsync(cancel);}
 public static async Task<string> Read(Stream stream,CancellationToken cancel){var header=new byte[4];await stream.ReadExactlyAsync(header,cancel);int length=System.Buffers.Binary.BinaryPrimitives.ReadInt32LittleEndian(header);if(length<1||length>16384)throw new IOException("Entry response budget");var bytes=new byte[length];await stream.ReadExactlyAsync(bytes,cancel);return Encoding.UTF8.GetString(bytes);}
 public static async Task<JsonObject> Send(string scope,string path,string id,int connectMs=500,int responseMs=15000){using var pipe=new NamedPipeClientStream(".","Confectory.Entry."+Key(scope),PipeDirection.InOut,PipeOptions.Asynchronous|PipeOptions.CurrentUserOnly);await pipe.ConnectAsync(connectMs);using var deadline=new CancellationTokenSource(responseMs);await Write(pipe,new JsonObject{["version"]=1,["id"]=id,["path"]=path}.ToJsonString(),deadline.Token);return JsonNode.Parse(await Read(pipe,deadline.Token))!.AsObject();}
 public static bool OwnerActive(string scope){string folder=Folder(scope);Directory.CreateDirectory(folder);try{using var file=new FileStream(Path.Combine(folder,"owner.lock"),FileMode.OpenOrCreate,FileAccess.ReadWrite,FileShare.None);return false;}catch(IOException){return true;}}
}
