#!/usr/bin/env python3
"""Actual Main controls, with an explicitly compiled owned simulated Provider only."""
from pathlib import Path
helper=Path(__file__).with_name('project_shell_x11.py')
source=helper.read_text();marker='try:\n    a=launch();';assert source.count(marker)==1
# Reuse X11/native-control harness without running its separate acceptance scenario.
exec(compile(source.split(marker)[0],str(helper),'exec'),globals())
def replace(window,control,text):
    click(window,control);field=json.loads(latest()['fields'][str(control)]);native_controls.key(int(field['nativeHandle']),'a',(0xFFE3,));type_text(window,text)
def clean(t):return not t['job'] and not t['model']['status'].startswith('Error:')
def approve(window):
    wait(lambda t:(t['model'].get('helperPanel') or {}).get('mode')=='ai-preview' and 22 in t['hits'][::5],'pinned approval panel')
    trace=wait(lambda t:'53' in t['fields'] and json.loads(t['fields']['53'])['visible'],'read-only exact approval content')
    content=json.loads(trace['fields']['53'])['text'];assert 'helperContext' in content and 'projectId' in content and 'rights' in content and 'owned-fixture' in content
    click(window,22)
try:
    a=launch();wait(lambda t:t['screen']=='intro','intro');click(a,1);click(a,2);click(a,10);type_text(a,'Owned AI GUI');click(a,13)
    state=wait(lambda t:t['screen']=='project' and clean(t),'owned project');context=state['model']['selected']['context'];path=state['model']['selected']['path'];ns=state['model']['selected']['namespace']
    click(a,8);wait(lambda t:(t['model'].get('helperPanel') or {}).get('mode')=='helpers','Helper panel');click(a,23);wait(lambda t:len(t['model']['helpers'])==1 and clean(t),'Main Helper');click(a,20);wait(lambda t:t['model'].get('helperContext') and clean(t),'Helper selected');click(a,42)
    leave_project(a);wait(lambda t:t['screen']=='home','hide');click(a,6);state=wait(lambda t:t['screen']=='manage' and t['model'].get('connections'),'connection choices');index=next(n for n,c in enumerate(state['model']['connections']['connections']) if c['id']=='Confectory.Agent.Responses::Connection');click(a,20+index)
    wait(lambda t:t['screen']=='project' and clean(t) and t['model'].get('workspace'),'settings');click(a,75);wait(lambda t:54 in t['hits'][::5],'settings Source');replace(a,54,'object Confectory.AISettings::Settings extends Confectory.Agent.Responses::Connection {data model = "owned-fixture"; data endpoint = "http://127.0.0.1:1/responses"; data credentialReference = "";}');click(a,58);wait(lambda t:clean(t) and t['model']['status'].startswith('Local source draft saved'),'save ordinary settings')
    leave_project(a);state=wait(lambda t:t['screen']=='home','hide settings');index=next(n for n,c in enumerate(state['model']['cards']) if c['path']==path);click(a,100+index*3);wait(lambda t:t['screen']=='project' and t['model']['selected']['context']==context,'return original project')
    click(a,6);state=wait(lambda t:(t['model'].get('helperPanel') or {}).get('mode')=='ai-connections','project connection panel');index=next(n for n,c in enumerate(state['model']['connections']['connections']) if c['id']=='Confectory.Agent.Responses::Connection');click(a,20+index);wait(lambda t:context in t['model']['aiBindings'] and clean(t),'bind declared settings');click(a,42)
    replace(a,38,'hello');click(a,41);wait(lambda t:t['model'].get('aiPreview') and clean(t),'chat approval');screenshot(a,'ai-chat-approval');approve(a);wait(lambda t:(t['model'].get('ai') or {}).get('state')=='completed','owned simulated chat');click(a,30);wait(lambda t:53 in t['hits'][::5] and 'Owned simulated assistant' in json.loads(t['fields']['53'])['text'],'actual selectable assistant output');screenshot(a,'ai-chat-output');click(a,39)
    click(a,55);wait(lambda t:t['model'].get('workspace') and clean(t),'open source workspace');click(a,73);replace(a,82,ns+'::ProjectInfo');click(a,83);wait(lambda t:t['model']['workspace']['selected']==ns+'::ProjectInfo' and clean(t),'select public proposal declaration')
    replace(a,38,'more local directions');click(a,17);click(a,22);wait(lambda t:t['model'].get('aiPreview') and clean(t),'proposal preview');screenshot(a,'ai-proposal-approval');approve(a);wait(lambda t:len((t['model'].get('ai') or {}).get('augment',{}).get('cards',[]))==3,'three validated owned simulated cards');click(a,17);wait(lambda t:23 in t['hits'][::5],'proposal cards');screenshot(a,'ai-three-cards');click(a,23);wait(lambda t:t['model'].get('selectedTaskContext')==context and clean(t),'select ordinary Worker task');click(a,26);approve(a)
    state=wait(lambda t:any(w.get('status')=='awaiting-verification' for w in (t['model'].get('ai') or {}).get('workers',{}).values()),'Worker awaits verification');task=state['model']['selectedTask'];staged=next(iter(state['model']['ai']['tools']['staged']));replace(a,82,staged);click(a,83);wait(lambda t:t['model']['workspace']['selected']==staged and clean(t),'inspect staged general source');click(a,64)
    wait(lambda t:t['model']['workspace'].get('review') and 208 in t['hits'][::5],'ordinary source review and explicit outcome evidence');replace(a,208,'Fixture user checked scoped source drafting and compiler; native outcome not exercised');screenshot(a,'ai-worker-source-review');click(a,209);wait(lambda t:(t['model'].get('ai') or {}).get('workers',{}).get(task,{}).get('status')=='completed' and len((t['model'].get('ai') or {}).get('developmentLog',[]))==1 and clean(t),'adoption compiler receipt and durable log',seconds=90)
    replace(a,82,ns+'::ProjectInfo');click(a,83);wait(lambda t:t['model']['workspace']['selected']==ns+'::ProjectInfo' and clean(t),'return semantic proposal target');replace(a,38,'next after adoption');click(a,17);click(a,22);approve(a);wait(lambda t:(t['model'].get('ai') or {}).get('proposalState')=='ready','next proposal batch sees adopted log');click(a,17);screenshot(a,'ai-next-proposals');click(a,25);wait(lambda t:t['model'].get('selectedTaskContext')==context and clean(t),'select active close test Worker');click(a,26);approve(a);wait(lambda t:any(w.get('status')=='running' for w in (t['model'].get('ai') or {}).get('workers',{}).values()),'active owned Worker');click(a,33);click(a,52);wait(lambda t:t['model'].get('closeRequest') and 66 in t['hits'][::5],'Worker complete-close prompt');screenshot(a,'ai-worker-close-prompt');click(a,66);wait(lambda t:t['model'].get('closeRequest') is None and (t['model'].get('ai') or {}).get('state')=='running','cancel keeps Worker');click(a,33);click(a,52);wait(lambda t:t['model'].get('closeRequest'),'repeat Worker close');click(a,65);state=wait(lambda t:t['screen']=='home' and context not in t['model']['aiRuns'],'confirmed Worker retirement');index=next(n for n,c in enumerate(state['model']['cards']) if c['path']==path);click(a,100+index*3);state=wait(lambda t:t['screen']=='project' and t['model']['selected']['path']==path,'reopen without Worker replay');context=state['model']['selected']['context'];assert state['model'].get('ai') is None
    click(a,6);state=wait(lambda t:(t['model'].get('helperPanel') or {}).get('mode')=='ai-connections','rebind after explicit reopen');index=next(n for n,c in enumerate(state['model']['connections']['connections']) if c['id']=='Confectory.Agent.Responses::Connection');click(a,20+index);wait(lambda t:context in t['model']['aiBindings'] and clean(t),'rebind saved settings');click(a,42)
    replace(a,38,'wait');click(a,41);approve(a);wait(lambda t:(t['model'].get('ai') or {}).get('state')=='running','active Agent');click(a,33);click(a,52);wait(lambda t:t['model'].get('closeRequest') and 66 in t['hits'][::5],'Agent complete-close prompt');click(a,66);wait(lambda t:t['model'].get('closeRequest') is None and (t['model'].get('ai') or {}).get('state')=='running','cancel keeps Agent');click(a,33);click(a,52);wait(lambda t:t['model'].get('closeRequest'),'repeat prompt');click(a,65);wait(lambda t:t['screen']=='home' and context not in t['model']['aiRuns'],'confirmed Agent retirement');end(a);app=None
    print('Actual Main AI chat / approval / scoped tools / three cards / direction reroll / Worker / selected Review / compiler adoption / development log / next proposals / Agent close UI PASS; owned simulated provider only')
finally:
    if app and app.poll() is None:
        os.killpg(app.pid,signal.SIGTERM);app.wait(timeout=30)
    if log and not log.closed:log.close()
    print('Owned AI GUI evidence:',storage)
