using Confectory.Core;
namespace Confectory.Tests;
public sealed class AIConnectionTests : TestCase
{
 public void test_declared_connection_settings_and_responses_approval_guards_without_network()
 {
 string sample=Path.Combine(f.Root,"connections");Fixture.CopyTree(Path.Combine(Fixture.Repo,"examples","edit-workspace"),sample);
 string project=Path.Combine(sample,"project.cpack"),manifest=File.ReadAllText(project).Replace("../../targets/dotnet/pack.cpack","../target/pack.cpack").Replace("../../packs/","../packs/");
 foreach(string name in new[]{"agent","ai-connection","agent-responses","agent-codex","development-tools","pack-workspace","file-stream","schema-editing","edit-workspace","save","change-set"}){Fixture.CopyTree(Path.Combine(Fixture.Repo,"packs",name),Path.Combine(f.Root,"packs",name));string pack=File.ReadAllText(Path.Combine(f.Root,"packs",name,"pack.cpack")).Split(" version ")[0].Replace("pack ","");if(!manifest.Contains("registry "+pack+" "))manifest=manifest.Replace("element Main function","registry "+pack+" \"../packs/"+name+"/pack.cpack\"; dependency "+pack+" version \"0.1.0\";\nelement Main function");}
 File.WriteAllText(Path.Combine(sample,"Counter.celem"),"object Example.EditWorkspace::Counter {value count = 0;}");manifest=manifest.Replace("element Main function","element Counter object \"Counter.celem\"; element Main function");File.WriteAllText(project,manifest);string main=Path.Combine(sample,"main.celem");File.WriteAllText(main,File.ReadAllText(main).Replace(" -> int {"," -> int {provide Confectory.Agent::Provider with Confectory.Agent.Responses::ProviderBody; use object Confectory.Agent.Responses::Connection; use object Confectory.Agent.Codex::Connection;"));
 File.WriteAllText(Path.Combine(sample,"main_body.celem"),"""
 implementation Example.EditWorkspace::MainBody for Example.EditWorkspace::Main () -> int {
 import Confectory.Agent.Responses::ValidateConfig as Validate (string) -> string;
 import Confectory.Agent::Provider as Provider (string,string,string,string) -> string;
 import Confectory.DevelopmentTools::Open as ToolsOpen (string,string,string,string,string) -> string;
 import Confectory.DevelopmentTools::Snapshot as ToolsSnapshot (string) -> string;
 import Confectory.DevelopmentTools::Close as ToolsClose (string) -> void;
 body common "main.csbody";}
 """);
 File.WriteAllText(Path.Combine(sample,"main.csbody"),"""
 string config="{\"provider\":\"responses\",\"protocol\":\"responses\",\"endpoint\":\"https://api.openai.com/v1/responses\",\"model\":\"explicit-model\",\"keyEnvironment\":\"CONFECTORY_AI_NOT_CONFIGURED\"}";
 var checkedConfig=System.Text.Json.Nodes.JsonNode.Parse(calls.Validate.Invoke(config))!;
 if(checkedConfig["networkContacted"]!.GetValue<bool>()||checkedConfig["credentialRead"]!.GetValue<bool>())throw new Exception("configuration performed IO");
 void Denied(Action action){try{action();}catch(ArgumentException){return;}catch(UnauthorizedAccessException){return;}throw new Exception("unsafe operation was accepted");}
 Denied(()=>calls.Validate.Invoke(config.Replace("https://api.openai.com/v1/responses","http://example.com/v1/responses")));
 Denied(()=>calls.Validate.Invoke(config.Replace("https://api.openai.com/v1/responses","https://user:secret@example.com/v1/responses")));
 Denied(()=>calls.Validate.Invoke(config.Replace("\"protocol\":","\"apiKey\":\"must-not-be-a-secret-field\",\"protocol\":")));
 string execution=Guid.NewGuid().ToString("N");try{Denied(()=>calls.Provider.Invoke(config,execution,"open","{}"));}finally{calls.Provider.Invoke(config,execution,"close","{}");}
 execution=Guid.NewGuid().ToString("N");try{Denied(()=>calls.Provider.Invoke(config,execution,"open","{\"authorization\":{\"projectId\":\"A\",\"contentApproved\":false}}"));}finally{calls.Provider.Invoke(config,execution,"close","{}");}
 // A local HTTP protocol fixture is not a model or live-provider validation.
 string project=Environment.GetEnvironmentVariable("CONFECTORY_TEST_CONNECTION_PROJECT")!;string capability=calls.ToolsOpen.Invoke(project,"A","Example.EditWorkspace","alice","editor");
 var listener=new System.Net.Sockets.TcpListener(System.Net.IPAddress.Loopback,0);listener.Start();int port=((System.Net.IPEndPoint)listener.LocalEndpoint).Port;var sent=new System.Collections.Generic.List<string>();
 var server=System.Threading.Tasks.Task.Run(()=>{for(int round=0;round<2;round++){using var client=listener.AcceptTcpClient();using var stream=client.GetStream();var header=new System.Text.StringBuilder();int c;while((c=stream.ReadByte())>=0){header.Append((char)c);if(header.ToString().EndsWith("\r\n\r\n",StringComparison.Ordinal))break;if(header.Length>16384)throw new Exception("header bound");}int length=int.Parse(System.Text.RegularExpressions.Regex.Match(header.ToString(),"Content-Length: ([0-9]+)",System.Text.RegularExpressions.RegexOptions.IgnoreCase).Groups[1].Value);var body=new byte[length];int offset=0;while(offset<length){int read=stream.Read(body,offset,length-offset);if(read==0)throw new Exception("short body");offset+=read;}sent.Add(System.Text.Encoding.UTF8.GetString(body));string response=round==0?new System.Text.Json.Nodes.JsonObject{["status"]="completed",["output"]=new System.Text.Json.Nodes.JsonArray(new System.Text.Json.Nodes.JsonObject{["type"]="function_call",["call_id"]="fixture-call",["name"]="workspace_stage",["arguments"]=new System.Text.Json.Nodes.JsonObject{["projectId"]="A",["id"]="Example.EditWorkspace::Counter",["expectedRevision"]=0,["text"]="object Example.EditWorkspace::Counter {value count = 2;}"}.ToJsonString()})}.ToJsonString():"{\"status\":\"completed\",\"output\":[{\"type\":\"message\",\"role\":\"assistant\",\"content\":[{\"type\":\"output_text\",\"text\":\"Fixture staged draft; user review required.\"}]}]}";byte[] bytes=System.Text.Encoding.UTF8.GetBytes(response),headers=System.Text.Encoding.ASCII.GetBytes("HTTP/1.1 200 OK\r\nContent-Type: application/json\r\nContent-Length: "+bytes.Length+"\r\nConnection: close\r\n\r\n");stream.Write(headers);stream.Write(bytes);}});
 string endpoint="http://127.0.0.1:"+port+"/v1/responses",localConfig=new System.Text.Json.Nodes.JsonObject{["provider"]="responses",["protocol"]="responses",["endpoint"]=endpoint,["model"]="protocol-fixture",["maxRounds"]=2}.ToJsonString();
 var input=new System.Text.Json.Nodes.JsonObject{["message"]="Owned protocol fixture only",["toolCapability"]=capability,["context"]=new System.Text.Json.Nodes.JsonObject{["projectId"]="A"},["authorization"]=new System.Text.Json.Nodes.JsonObject{["projectId"]="A",["contentApproved"]=true,["endpoint"]=endpoint,["model"]="protocol-fixture"}};
 execution=Guid.NewGuid().ToString("N");try{string original=System.IO.File.ReadAllText(System.IO.Path.Combine(System.IO.Path.GetDirectoryName(project)!,"Counter.celem"));calls.Provider.Invoke(localConfig,execution,"open",new System.Text.Json.Nodes.JsonObject{["kind"]="worker-task",["project"]="A",["ownerHelper"]="chief",["input"]=input}.ToJsonString());bool completed=false;string output="";for(int n=0;n<600;n++){var item=System.Text.Json.Nodes.JsonNode.Parse(calls.Provider.Invoke(localConfig,execution,"next","{}"))!;if(item["kind"]!.ToString()=="error")throw new Exception("protocol fixture failed");if(item["kind"]!.ToString()=="delta")output+=item["text"]!.ToString();if(item["kind"]!.ToString()=="completed"){completed=true;break;}System.Threading.Thread.Sleep(10);}if(!completed||!output.Contains("review required")||!server.Wait(3000))throw new Exception("transport rounds did not finish");if(sent.Count!=2||System.Linq.Enumerable.Any(sent,text=>text.Contains(capability)||text.Contains("authorization")||text.Contains("credentialReference")))throw new Exception("local capability or auth leaked");if(!sent[1].Contains("function_call_output")||System.IO.File.ReadAllText(System.IO.Path.Combine(System.IO.Path.GetDirectoryName(project)!,"Counter.celem"))!=original||System.Text.Json.Nodes.JsonNode.Parse(calls.ToolsSnapshot.Invoke(capability))!["staged"]!["Example.EditWorkspace::Counter"] is null)throw new Exception("tool roundtrip bypassed draft boundary");}finally{calls.Provider.Invoke(localConfig,execution,"close","{}");calls.ToolsClose.Invoke(capability);listener.Stop();}
 Console.WriteLine("Connection declarations / approval guards / local HTTP fixture / draft-only tool roundtrip PASS");return 0;
 """);
 string? oldProject=Environment.GetEnvironmentVariable("CONFECTORY_TEST_CONNECTION_PROJECT"),oldHost=Environment.GetEnvironmentVariable("CONFECTORY_ELEMENT_AUTHORING_HOST");try{Environment.SetEnvironmentVariable("CONFECTORY_ELEMENT_AUTHORING_HOST",Path.Combine(Fixture.Repo,"targets","element-authoring","bin","Release","net10.0","Confectory.ElementAuthoring.dll"));Environment.SetEnvironmentVariable("CONFECTORY_TEST_CONNECTION_PROJECT",project);var built=new Builder(project,"portable").Build();Output(built,"Connection declarations / approval guards / local HTTP fixture / draft-only tool roundtrip PASS");File.AppendAllText(Path.Combine(f.Root,"packs","agent-responses","ValidateConfig.csbody"),"\n// connection configuration locality\n");var changed=new Builder(project,"portable").Build();PackRebuilt(changed,new[]{"Confectory.Agent.Responses::ValidateConfigBody"});Equal(0,Strings(changed,"statistics","compiledContracts").Length);}finally{Environment.SetEnvironmentVariable("CONFECTORY_TEST_CONNECTION_PROJECT",oldProject);Environment.SetEnvironmentVariable("CONFECTORY_ELEMENT_AUTHORING_HOST",oldHost);}
 }
}
