using System.Diagnostics;
using System.Text.Json.Nodes;
using Confectory.Core;
namespace Confectory.Tests;
public sealed class AugmentTests : TestCase
{
 public void test_registered_augment_is_inactive_without_public_contract_selection()
 {
  string packs=Path.Combine(f.Root,"optional-packs");Fixture.CopyTree(Path.Combine(Fixture.Repo,"packs"),packs);foreach(string manifest in Directory.EnumerateFiles(packs,"pack.cpack",SearchOption.AllDirectories)){string ns=File.ReadAllText(manifest).Split((char[]?)null,StringSplitOptions.RemoveEmptyEntries)[1];f.ExtraRegistry[ns]=manifest;}f.Packs["App"].Dependencies["Confectory.Augment"]="0.1.0";f.Sync();File.WriteAllText(Path.Combine(packs,"augment","Command.csbody"),"deliberately invalid unselected optional implementation");var built=new Builder(f.Project,"linux").Build();True(!Strings(built,"statistics","compiledImplementations").Any(id=>id.StartsWith("Confectory.Augment::",StringComparison.Ordinal)));File.AppendAllText(Path.Combine(packs,"augment","Command.csbody")," more invalid text");var changed=new Builder(f.Project,"linux").Build();Equal(0,Strings(changed,"statistics","compiledImplementations").Length);Equal(0,Strings(changed,"statistics","compiledContracts").Length);
 }
 public void test_chief_only_proposals_drafts_verification_history_and_locality()
 {
  string sample=Path.Combine(f.Root,"consumer");Fixture.CopyTree(Path.Combine(Fixture.Repo,"examples","augment"),sample);Fixture.CopyTree(Path.Combine(Fixture.Repo,"packs"),Path.Combine(f.Root,"packs"));string project=Path.Combine(sample,"project.cpack");File.WriteAllText(project,File.ReadAllText(project).Replace("../../packs/","../packs/",StringComparison.Ordinal).Replace("../../targets/dotnet/pack.cpack","../target/pack.cpack",StringComparison.Ordinal));string source=Path.Combine(f.Root,"source");Fixture.CopyTree(Path.Combine(Fixture.Repo,"examples","projects","harvest-game"),source);string sourceProject=Path.Combine(source,"project.cpack");File.WriteAllText(sourceProject,File.ReadAllText(sourceProject).Replace("../../../packs/","../packs/",StringComparison.Ordinal).Replace("../../../targets/dotnet/pack.cpack","../target/pack.cpack",StringComparison.Ordinal));var built=new Builder(project,"linux").Build();string[] command=Strings(built,"run");var info=new ProcessStartInfo(command[0]){UseShellExecute=false,RedirectStandardOutput=true,RedirectStandardError=true};foreach(string arg in command.Skip(1))info.ArgumentList.Add(arg);info.Environment["CONFECTORY_AUGMENT_PROJECT"]=sourceProject;info.Environment["CONFECTORY_AUGMENT_MODE"]="functional";info.Environment["CONFECTORY_AUGMENT_DIR"]=Path.Combine(f.Root,"state");info.Environment["CONFECTORY_ELEMENT_AUTHORING_HOST"]=Path.Combine(Fixture.Repo,"targets","element-authoring","bin","Release","net8.0","Confectory.ElementAuthoring.dll");using var process=Process.Start(info)!;var output=process.StandardOutput.ReadToEndAsync();var error=process.StandardError.ReadToEndAsync();try{System.Threading.Tasks.Task.WhenAll(output,error).WaitAsync(TimeSpan.FromSeconds(180)).GetAwaiter().GetResult();True(process.WaitForExit(5000)&&process.ExitCode==0,error.Result+output.Result);True(output.Result.Contains("actual source/domain verification PASS",StringComparison.Ordinal),output.Result);True(output.Result.Contains("stale/deletion/cancelled generation PASS",StringComparison.Ordinal),output.Result);}finally{if(!process.HasExited)process.Kill(true);}
  File.AppendAllText(Path.Combine(f.Root,"packs","augment","Command.csbody"),"\n// selected owning augment policy locality\n");var changed=new Builder(project,"linux").Build();Sequence(new[]{"Confectory.Augment::CommandBody"},Strings(changed,"statistics","compiledImplementations"));Equal(0,Strings(changed,"statistics","compiledContracts").Length);File.AppendAllText(Path.Combine(f.Root,"packs","augment","Provider.csbody"),"\n// unselected default provider\n");var excluded=new Builder(project,"linux").Build();Equal(0,Strings(excluded,"statistics","compiledImplementations").Length);File.WriteAllText(Path.Combine(sample,"Main.celem"),File.ReadAllText(Path.Combine(sample,"Main.celem")).Replace("provide Confectory.Augment::Provider with Example.Augment::Creative;","provide Confectory.Augment::Provider with Confectory.Augment::ProviderBody;",StringComparison.Ordinal));var defaultBuild=new Builder(project,"linux").Build();string[] defaultCommand=Strings(defaultBuild,"run");var defaultInfo=new ProcessStartInfo(defaultCommand[0]){UseShellExecute=false,RedirectStandardOutput=true,RedirectStandardError=true};foreach(string arg in defaultCommand.Skip(1))defaultInfo.ArgumentList.Add(arg);defaultInfo.Environment["CONFECTORY_AUGMENT_PROJECT"]=sourceProject;defaultInfo.Environment["CONFECTORY_AUGMENT_MODE"]="default-refusal";defaultInfo.Environment["CONFECTORY_AUGMENT_DIR"]=Path.Combine(f.Root,"default-state");defaultInfo.Environment["CONFECTORY_ELEMENT_AUTHORING_HOST"]=info.Environment["CONFECTORY_ELEMENT_AUTHORING_HOST"];using var defaultProcess=Process.Start(defaultInfo)!;var defaultOutput=defaultProcess.StandardOutput.ReadToEndAsync();var defaultError=defaultProcess.StandardError.ReadToEndAsync();try{System.Threading.Tasks.Task.WhenAll(defaultOutput,defaultError).WaitAsync(TimeSpan.FromSeconds(30)).GetAwaiter().GetResult();True(defaultProcess.WaitForExit(5000)&&defaultProcess.ExitCode==0,defaultOutput.Result+defaultError.Result);True(defaultOutput.Result.Contains("unconfigured default refuses generation PASS",StringComparison.Ordinal),defaultOutput.Result);}finally{if(!defaultProcess.HasExited)defaultProcess.Kill(true);}
 }
}
