using Confectory.Core;
namespace Confectory.Tests;
public sealed class PackWorkspaceTests : TestCase
{
 public void test_two_contexts_revision_save_reopen_and_locality()
 {
 string sample=Path.Combine(f.Root,"workspace-consumer");Fixture.CopyTree(Path.Combine(Fixture.Repo,"examples","edit-workspace"),sample);
 foreach(string name in new[]{"file-stream","schema-editing","edit-workspace","save","change-set","pack-workspace"})Fixture.CopyTree(Path.Combine(Fixture.Repo,"packs",name),Path.Combine(f.Root,"packs",name));
 string project=Path.Combine(sample,"project.cpack");File.WriteAllText(project,File.ReadAllText(project).Replace("../../packs/","../packs/").Replace("../../targets/dotnet/pack.cpack","../target/pack.cpack").Replace("element Main function", "registry Confectory.PackWorkspace \"../packs/pack-workspace/pack.cpack\"; dependency Confectory.PackWorkspace version \"0.1.0\";\nelement Main function"));

 for(int i=0;i<40;i++){string name="ZItem"+i.ToString("D2");f.Add("App","object",name,"object App::"+name+" {}");}f.Sync();

 File.WriteAllText(Path.Combine(sample,"main_body.celem"),"""
 implementation Example.EditWorkspace::MainBody for Example.EditWorkspace::Main () -> int {
 import Confectory.PackWorkspace::Open as Open (string,string,string) -> string;
 import Confectory.PackWorkspace::Snapshot as Snapshot (string) -> string;
 import Confectory.PackWorkspace::Command as Command (string,string,string) -> string;
 import Confectory.PackWorkspace::Close as Close (string) -> void;
 body common "main.csbody";
 }
 """);
 File.WriteAllText(Path.Combine(sample,"main.csbody"),"""
 string project=Environment.GetEnvironmentVariable("CONFECTORY_TEST_AUTHOR_PROJECT")!;
 string a=calls.Open.Invoke(project,"alice","one"),b=calls.Open.Invoke(project,"alice","two");
 var initial=System.Text.Json.Nodes.JsonNode.Parse(calls.Snapshot.Invoke(a))!;
 if(!System.Linq.Enumerable.Any(initial["units"]!.AsArray(),x=>x!["materialization"]!.GetValue<string>()=="deferred"))throw new Exception("Snapshot materialized every owned unit");
 string id=System.Linq.Enumerable.First(initial["units"]!.AsArray(),x=>x!["kind"]!.GetValue<string>()=="body")!["id"]!.GetValue<string>();
 string Select(string h)=>calls.Command.Invoke(h,"select",System.Text.Json.JsonSerializer.Serialize(new{id}));
 string original=System.Text.Json.Nodes.JsonNode.Parse(Select(a))!["unit"]!["text"]!.GetValue<string>();Select(b);
 var filtered=System.Text.Json.Nodes.JsonNode.Parse(calls.Command.Invoke(a,"filter",System.Text.Json.JsonSerializer.Serialize(new{query=id.ToUpperInvariant(),kind="body"})))!;
 if(filtered["total"]!.GetValue<int>()!=1||filtered["unit"]!["id"]!.ToString()!=id||filtered["ownedTotal"]!.GetValue<int>()!=initial["total"]!.GetValue<int>())throw new Exception("Stable ID/kind filter failed");
 var empty=System.Text.Json.Nodes.JsonNode.Parse(calls.Command.Invoke(a,"filter","{\"query\":\"missing::unit\"}"))!;
 if(empty["total"]!.GetValue<int>()!=0||empty["units"]!.AsArray().Count!=0||empty["unit"]!["id"]!.ToString()!=id)throw new Exception("Empty filter lost selection");
 if(System.Text.Json.Nodes.JsonNode.Parse(calls.Snapshot.Invoke(b))!["query"]!.ToString()!="")throw new Exception("View filter leaked");
 var page=System.Text.Json.Nodes.JsonNode.Parse(calls.Command.Invoke(a,"page","{\"page\":999}"))!;if(page["page"]!.GetValue<int>()!=0)throw new Exception("Empty page not clamped");
 bool longRejected=false;try{calls.Command.Invoke(a,"filter",System.Text.Json.JsonSerializer.Serialize(new{query=new string('x',257)}));}catch(ArgumentException){longRejected=true;}if(!longRejected)throw new Exception("Unbounded filter accepted");
 calls.Command.Invoke(a,"select","{\"id\":\"App::ZItem00\"}");
 var declared=System.Text.Json.Nodes.JsonNode.Parse(calls.Command.Invoke(a,"inspect","{}"))!;if(declared["inspection"]!["relations"]!["edges"]!.AsArray().Count!=0||declared["inspectionRevision"]!.GetValue<long>()!=0)throw new Exception("Empty declaration inspection");
 calls.Command.Invoke(a,"edit",System.Text.Json.JsonSerializer.Serialize(new{text="object App::ZItem00 extends Missing::Parent { module Missing::Role; }",expectedRevision=0}));
 var changedInspection=System.Text.Json.Nodes.JsonNode.Parse(calls.Command.Invoke(a,"inspect","{}"))!;if(changedInspection["inspection"]!["relations"]!["edges"]!.AsArray().Count!=2||changedInspection["inspectionRevision"]!.GetValue<long>()!=1)throw new Exception("Inspection ignored selected draft");
 Select(a);bool bodyRefused=false;try{calls.Command.Invoke(a,"inspect","{}");}catch(InvalidOperationException){bodyRefused=true;}if(!bodyRefused)throw new Exception("Body treated as declaration");
 var objects=System.Text.Json.Nodes.JsonNode.Parse(calls.Command.Invoke(a,"filter","{\"kind\":\"object\"}"))!;if(objects["total"]!.GetValue<int>()!=40||objects["units"]!.AsArray().Count!=32)throw new Exception("Kind pagination first page");
 var last=System.Text.Json.Nodes.JsonNode.Parse(calls.Command.Invoke(a,"page","{\"page\":1}"))!;if(last["units"]!.AsArray().Count!=8||last["units"]![0]!["id"]!.ToString()!="App::ZItem32")throw new Exception("Stable filtered page ordering");
 var reset=System.Text.Json.Nodes.JsonNode.Parse(calls.Command.Invoke(a,"filter","{}"))!;if(reset["total"]!.GetValue<int>()!=initial["total"]!.GetValue<int>()||reset["page"]!.GetValue<int>()!=0)throw new Exception("Filter reset failed");

 string edited=original+"\n// local draft one\n";
 string Edit(string h,long revision,string text)=>calls.Command.Invoke(h,"edit",System.Text.Json.JsonSerializer.Serialize(new{expectedRevision=revision,text}));
 if(System.Text.Json.Nodes.JsonNode.Parse(Edit(a,0,edited))!["conflict"]!.GetValue<bool>())throw new Exception("Unexpected conflict");
 if(!System.Text.Json.Nodes.JsonNode.Parse(Edit(a,0,"stale"))!["conflict"]!.GetValue<bool>())throw new Exception("Stale edit accepted");
 if(System.Text.Json.Nodes.JsonNode.Parse(calls.Snapshot.Invoke(b))!["unit"]!["text"]!.GetValue<string>()!=original)throw new Exception("Contexts leaked");
 string shared=calls.Open.Invoke(project,"alice","one");if(System.Text.Json.Nodes.JsonNode.Parse(Select(shared))!["unit"]!["text"]!.GetValue<string>()!=edited)throw new Exception("Same identity lost live draft");calls.Command.Invoke(a,"filter","{\"query\":\"missing::unit\"}");if(System.Text.Json.Nodes.JsonNode.Parse(calls.Snapshot.Invoke(shared))!["query"]!.ToString()!="")throw new Exception("Same-draft view filter leaked");calls.Command.Invoke(a,"filter","{}");calls.Close.Invoke(shared);calls.Close.Invoke(shared);
 calls.Command.Invoke(a,"select",System.Text.Json.JsonSerializer.Serialize(new{id=initial["units"]![0]!["id"]!.GetValue<string>()}));if(System.Text.Json.Nodes.JsonNode.Parse(Select(a))!["unit"]!["text"]!.GetValue<string>()!=edited)throw new Exception("Selection discarded draft");
 calls.Command.Invoke(a,"save","{}");string owned=System.Text.Json.Nodes.JsonNode.Parse(calls.Snapshot.Invoke(a))!["unit"]!["path"]!.GetValue<string>();if(System.IO.File.ReadAllText(System.IO.Path.Combine(System.IO.Path.GetDirectoryName(project)!,owned))!=original)throw new Exception("Save modified final source");calls.Close.Invoke(a);calls.Close.Invoke(a);
 a=calls.Open.Invoke(project,"alice","one");if(System.Text.Json.Nodes.JsonNode.Parse(Select(a))!["unit"]!["text"]!.GetValue<string>()!=edited)throw new Exception("Draft lost on reopen");
 var sources=System.Text.Json.Nodes.JsonNode.Parse(calls.Command.Invoke(a,"sources","{}"))!["files"]!.AsArray();if(!System.Linq.Enumerable.Any(sources,x=>x!["kind"]!.GetValue<string>()=="project"))throw new Exception("Manifest missing");
 var review=System.Text.Json.Nodes.JsonNode.Parse(calls.Command.Invoke(a,"review","{\"target\":\"portable\"}"))!["review"]!;
 if(review["status"]!.ToString()!="ready"||review["path"]!.ToString()!=owned||review["before"]!.ToString()!=original||review["after"]!.ToString()!=edited)throw new Exception("Review omitted owned path or exact source values");
 var reviewFiltered=System.Text.Json.Nodes.JsonNode.Parse(calls.Command.Invoke(a,"filter","{\"query\":\"missing::unit\"}"))!;if(reviewFiltered["review"]!["token"]!.ToString()!=review["token"]!.ToString()||reviewFiltered["unit"]!["text"]!.ToString()!=edited)throw new Exception("Navigation mutated reviewed draft");calls.Command.Invoke(a,"filter","{}");
 bool rejected=false;try{calls.Command.Invoke(a,"confirm","{\"token\":\"forged\"}");}catch(InvalidOperationException){rejected=true;}if(!rejected)throw new Exception("Confirm bypassed review token");
 string reviewedToken=review["token"]!.ToString(),next=edited+"\n// after-review change\n";long revision=long.Parse(review["revision"]!.ToString());Edit(a,revision,next);
 rejected=false;try{calls.Command.Invoke(a,"confirm",System.Text.Json.JsonSerializer.Serialize(new{token=reviewedToken}));}catch(InvalidOperationException){rejected=true;}if(!rejected)throw new Exception("Changed draft confirmed with old review token");
 calls.Command.Invoke(a,"review","{\"target\":\"portable\"}");calls.Command.Invoke(a,"cancel-review","{}");var cancelled=System.Text.Json.Nodes.JsonNode.Parse(calls.Snapshot.Invoke(a))!;
 if(cancelled["review"] is not null||cancelled["unit"]!["text"]!.ToString()!=next||System.IO.File.ReadAllText(System.IO.Path.Combine(System.IO.Path.GetDirectoryName(project)!,owned))!=original)throw new Exception("Cancel modified final source or discarded draft");
 var groupIds=new[]{id,"App::ZItem01"};var peerReview=System.Text.Json.Nodes.JsonNode.Parse(calls.Command.Invoke(a,"review",System.Text.Json.JsonSerializer.Serialize(new{target="portable",ids=groupIds})))!;string peerToken=peerReview["review"]!["token"]!.ToString();
 string concurrent=calls.Open.Invoke(project,"alice","one");var peerSelected=System.Text.Json.Nodes.JsonNode.Parse(Select(concurrent))!;long peerRevision=peerSelected["unit"]!["revision"]!.GetValue<long>();string peerText=peerSelected["unit"]!["text"]!.ToString()+"\n// shared peer edit after group review\n";Edit(concurrent,peerRevision,peerText);
 bool staleGroup=false;try{calls.Command.Invoke(a,"confirm",System.Text.Json.JsonSerializer.Serialize(new{token=peerToken,ids=groupIds}));}catch(InvalidOperationException){staleGroup=true;}var staleSnapshot=System.Text.Json.Nodes.JsonNode.Parse(calls.Snapshot.Invoke(a))!;if(!staleGroup||staleSnapshot["review"]!["status"]!.ToString()!="stale"||staleSnapshot["review"]!["token"]!.ToString()!=""||System.IO.File.ReadAllText(System.IO.Path.Combine(System.IO.Path.GetDirectoryName(project)!,owned))!=original)throw new Exception("Shared peer group change bypassed exact reviewed state");calls.Close.Invoke(concurrent);
 var freshGroup=System.Text.Json.Nodes.JsonNode.Parse(calls.Command.Invoke(a,"review",System.Text.Json.JsonSerializer.Serialize(new{target="portable",ids=groupIds})))!;var appliedGroup=System.Text.Json.Nodes.JsonNode.Parse(calls.Command.Invoke(a,"confirm",System.Text.Json.JsonSerializer.Serialize(new{token=freshGroup["review"]!["token"]!.ToString(),ids=groupIds})))!;if(appliedGroup["confirmation"]![0]!.ToString()!="confirmed"||System.IO.File.ReadAllText(System.IO.Path.Combine(System.IO.Path.GetDirectoryName(project)!,owned))!=peerText)throw new Exception("Explicitly reviewed peer retry failed: "+appliedGroup.ToJsonString());
 calls.Close.Invoke(a);calls.Close.Invoke(b);Console.WriteLine("PackWorkspace independent contexts/revision/save/reopen PASS");return 0;
 """);
 string? host=Environment.GetEnvironmentVariable("CONFECTORY_ELEMENT_AUTHORING_HOST"),selected=Environment.GetEnvironmentVariable("CONFECTORY_TEST_AUTHOR_PROJECT");
 try{Environment.SetEnvironmentVariable("CONFECTORY_ELEMENT_AUTHORING_HOST",Path.Combine(Fixture.Repo,"targets","element-authoring","bin","Release","net10.0","Confectory.ElementAuthoring.dll"));Environment.SetEnvironmentVariable("CONFECTORY_TEST_AUTHOR_PROJECT",f.Project);
 var built=new Builder(project,"portable").Build();Output(built,"PackWorkspace independent contexts/revision/save/reopen PASS");
 File.AppendAllText(Path.Combine(f.Root,"packs","pack-workspace","Snapshot.csbody"),"\n// locality\n");var changed=new Builder(project,"portable").Build();PackRebuilt(changed, new[]{"Confectory.PackWorkspace::SnapshotBody"});Equal(0,Strings(changed,"statistics","compiledContracts").Length);
 File.AppendAllText(Path.Combine(f.Root,"packs","pack-workspace","Command.csbody"),"\n// selected-inspection locality\n");var commandChanged=new Builder(project,"portable").Build();PackRebuilt(commandChanged,new[]{"Confectory.PackWorkspace::CommandBody"});Equal(0,Strings(commandChanged,"statistics","compiledContracts").Length);
 }finally{Environment.SetEnvironmentVariable("CONFECTORY_ELEMENT_AUTHORING_HOST",host);Environment.SetEnvironmentVariable("CONFECTORY_TEST_AUTHOR_PROJECT",selected);}
 }
 public void test_target_metadata_owned_sources_no_registry_execution()
 {
 string folder=Path.Combine(f.Root,"metadata-adapter");Directory.CreateDirectory(folder);
 foreach(string target in new[]{"android-export","browser-wasm"})
 {
 string source=File.ReadAllText(Path.Combine(Fixture.Repo,"targets",target,"templates","MetadataAuthoring.cs"));
 if(target=="browser-wasm")Equal(File.ReadAllText(Path.Combine(Fixture.Repo,"targets","android-export","templates","MetadataAuthoring.cs")),source);
 }
 File.Copy(Path.Combine(Fixture.Repo,"targets","android-export","templates","MetadataAuthoring.cs"),Path.Combine(folder,"MetadataAuthoring.cs"));
 string core=System.Security.SecurityElement.Escape(typeof(Builder).Assembly.Location)!;
 File.WriteAllText(Path.Combine(folder,"check.csproj"),$"<Project Sdk=\"Microsoft.NET.Sdk\"><PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net10.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable></PropertyGroup><ItemGroup><Reference Include=\"Confectory.Core\"><HintPath>{core}</HintPath></Reference></ItemGroup></Project>");
 File.WriteAllText(Path.Combine(folder,"Program.cs"),"""
 using System.Text.Json.Nodes;
 string root=Path.Combine(Path.GetTempPath(),"confectory-metadata-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(root);
 try {
 File.WriteAllText(Path.Combine(root,"project.cpack"),"project Any.Renamed version \"0.1.0\" { standalone true; registry Evil \"../../missing-do-not-read.cpack\"; element Main function \"main.celem\"; element MainBody implementation \"body.celem\"; }");
 File.WriteAllText(Path.Combine(root,"main.celem"),"function Any.Renamed::Main () -> int { }");
 File.WriteAllText(Path.Combine(root,"body.celem"),"implementation Any.Renamed::MainBody for Any.Renamed::Main () -> int { body common \"main.csbody\"; }");File.WriteAllText(Path.Combine(root,"main.csbody"),"throw new Exception(\"never execute\");");
 string lazyPayload=System.Text.Json.JsonSerializer.Serialize(new{project=Path.Combine(root,"project.cpack"),metadataOnly=true});
 File.Delete(Path.Combine(root,"main.celem"));File.Delete(Path.Combine(root,"main.csbody"));
 var lazyDescription=JsonNode.Parse(MetadataAuthoring.Call(root,"describe",lazyPayload))!;if(lazyDescription["units"]!.AsArray().Count!=4)throw new Exception("Locator description reads deferred declarations or body bytes");
 var bodyMetadata=JsonNode.Parse(MetadataAuthoring.Call(root,"bodyUnits",System.Text.Json.JsonSerializer.Serialize(new{project=Path.Combine(root,"project.cpack"),id="Any.Renamed::MainBody",path="body.celem",text=File.ReadAllText(Path.Combine(root,"body.celem"))})))!;
 if(bodyMetadata["units"]![0]!["id"]!.ToString()!="Any.Renamed::MainBody/body:common")throw new Exception("Draft implementation body navigation");
 File.WriteAllText(Path.Combine(root,"main.celem"),"function Any.Renamed::Main () -> int { }");File.WriteAllText(Path.Combine(root,"main.csbody"),"throw new Exception(\"never execute\");");
 string payload=System.Text.Json.JsonSerializer.Serialize(new{project=Path.Combine(root,"project.cpack")});var metadata=JsonNode.Parse(MetadataAuthoring.Call(root,"describe",payload))!;
 if(metadata["units"]!.AsArray().Count!=4)throw new Exception("Owned unit description");
 var inspected=JsonNode.Parse(MetadataAuthoring.Call(root,"inspect","{\"text\":\"object Any.Renamed::Value { }\"}"))!;if(inspected["id"]!.GetValue<string>()!="Any.Renamed::Value")throw new Exception("Inspect identity");
 string schemaSource="schema Any.Renamed::Shape { field enabled single general bool; field peers multiple reference Any.Renamed::Shape; }";
 var schemaInspect=JsonNode.Parse(MetadataAuthoring.Call(root,"inspect",System.Text.Json.JsonSerializer.Serialize(new{text=schemaSource})))!;if(schemaInspect["fields"]!.AsObject().Count!=2)throw new Exception("Native direct schema projection");
 string preserved=System.Text.Json.JsonSerializer.Deserialize<string>(MetadataAuthoring.Call(root,"setValue",System.Text.Json.JsonSerializer.Serialize(new{text=schemaSource,field="legacy",value=false})))!;
 if(!preserved.Contains("field peers multiple reference Any.Renamed::Shape;",StringComparison.Ordinal))throw new Exception("Scalar formatter discarded typed fields");
 string typedDraft=System.Text.Json.JsonSerializer.Deserialize<string>(MetadataAuthoring.Call(root,"setData",System.Text.Json.JsonSerializer.Serialize(new{text="object Any.Renamed::O { value old = 0; }",field="peers",value=new[]{new System.Collections.Generic.Dictionary<string,string>{{"$ref","Any.Renamed::Other"}}}})))!;
 if(!typedDraft.Contains("data peers = [Any.Renamed::Other];",StringComparison.Ordinal)||!typedDraft.Contains("value old = 0;",StringComparison.Ordinal))throw new Exception("Native typed transport direct syntax preservation");
 var typedParsed=JsonNode.Parse(MetadataAuthoring.Call(root,"inspect",System.Text.Json.JsonSerializer.Serialize(new{text=typedDraft})))!;if(typedParsed["data"]!["peers"]!["Items"]![0]!["Reference"]!.ToString()!="Any.Renamed::Other")throw new Exception("Native typed reference projection");
 var relationships=JsonNode.Parse(MetadataAuthoring.Call(root,"inspect",System.Text.Json.JsonSerializer.Serialize(new{text="module Any.Renamed::Rules extends Missing::Parent { module Missing::Role; include Missing::Child; require Missing::Function (int) -> int; default Missing::Function with Missing::Body; provide Missing::Function with Missing::Explicit; }"})))!["relations"]!;
 if(relationships["scope"]!.ToString()!="declared"||relationships["edges"]!.AsArray().Count!=6||!System.Linq.Enumerable.Any(relationships["edges"]!.AsArray(),e=>e!["role"]!.ToString()=="provide"&&e["target"]!.ToString()=="Missing::Explicit"&&e["function"]!.ToString()=="Missing::Function"))throw new Exception("Target direct relationship contract");
 string typedSource="implementation Any.Renamed::Work for Missing::Own () -> int { use schema Missing::Shape; contain object Missing::Child; import Missing::Fn as A (string,int[]) -> bool in Missing::Scope; import Missing::Fn as B (string,int[]) -> bool; body common \"must-not-read.csbody\"; }";
 var typedRelations=JsonNode.Parse(MetadataAuthoring.Call(root,"inspect",System.Text.Json.JsonSerializer.Serialize(new{text=typedSource})))!["relations"]!;
 var typedEdges=typedRelations["edges"]!.AsArray();if(typedEdges.Count!=4||typedEdges[0]!["role"]!.ToString()!="contain"||typedEdges[0]!["kind"]!.ToString()!="object"||typedEdges[1]!["alias"]!.ToString()!="A"||typedEdges[1]!["scope"]!.ToString()!="Missing::Scope"||typedEdges[2]!["alias"]!.ToString()!="B"||typedEdges[2]!["scope"] is not null||typedEdges[3]!["kind"]!.ToString()!="schema"||typedEdges[1]!["signature"]!["return"]!.ToString()!="bool")throw new Exception("Declared typed/scoped imports without target reads");
 foreach(var contract in new[]{"() -> void","(string,int[],bool) -> string[]","(long[],double,float[]) -> bool"}){
 var requirement=JsonNode.Parse(MetadataAuthoring.Call(root,"inspect",System.Text.Json.JsonSerializer.Serialize(new{text="module Any.Renamed::Rules { require Missing::Function "+contract+"; }"})))!["relations"]!["edges"]![0]!;
 string named=contract.Replace("string,int[],bool","string arg0,int[] arg1,bool arg2",StringComparison.Ordinal).Replace("long[],double,float[]","long[] arg0,double arg1,float[] arg2",StringComparison.Ordinal);
 var signature=JsonNode.Parse(MetadataAuthoring.Call(root,"inspect",System.Text.Json.JsonSerializer.Serialize(new{text="function Missing::Function "+named+" {}"})))!["signature"];
 if(!JsonNode.DeepEquals(requirement["signature"],signature))throw new Exception("Target required signature format");
 }
 string created=System.Text.Json.JsonSerializer.Deserialize<string>(MetadataAuthoring.Call(root,"create",System.Text.Json.JsonSerializer.Serialize(new{kind="object",id="Any.Renamed::ProjectInfo"})))!;
 string changed=System.Text.Json.JsonSerializer.Deserialize<string>(MetadataAuthoring.Call(root,"setValue",System.Text.Json.JsonSerializer.Serialize(new{text=created,field="title",value="한글 🧁"})))!;
 if(JsonNode.Parse(MetadataAuthoring.Call(root,"inspect",System.Text.Json.JsonSerializer.Serialize(new{text=changed})))!["values"]!["title"]!.GetValue<string>()!="한글 🧁")throw new Exception("Scalar edit lost");
 string registered=System.Text.Json.JsonSerializer.Deserialize<string>(MetadataAuthoring.Call(root,"register",System.Text.Json.JsonSerializer.Serialize(new{text=File.ReadAllText(Path.Combine(root,"project.cpack")),id="Any.Renamed::ProjectInfo",kind="object",path="elements/ProjectInfo.celem"})))!;
 if(!registered.Contains("elements/ProjectInfo.celem",StringComparison.Ordinal)||!registered.Contains("../../missing-do-not-read.cpack",StringComparison.Ordinal))throw new Exception("Registration changed unrelated metadata");
 bool refused=false;try{MetadataAuthoring.Call(root,"validate",payload);}catch(PlatformNotSupportedException){refused=true;}if(!refused)throw new Exception("Compiler operation accepted");
 refused=false;try{MetadataAuthoring.Call(root,"describe",System.Text.Json.JsonSerializer.Serialize(new{project=Path.Combine(root,"..","outside.cpack")}));}catch{refused=true;}if(!refused)throw new Exception("Owned root escaped");
 string locatorManifest="project Any.Renamed version \"0.1.0\" { registry Known \"known.cpack\"; registry Broken \"missing.cpack\"; registry Unused \"must-not-read.cpack\"; element Value object \"not-read.celem\"; }";
 string knownManifest="pack Known version \"0.1.0\" { element Good module \"not-opened.celem\"; }";File.WriteAllText(Path.Combine(root,"known.cpack"),knownManifest);
 string[] requested={"Any.Renamed::Value","Any.Renamed::Absent","Known::Good","Known::Absent","Broken::Thing","Unknown::Thing","bad-id"};
 var located=JsonNode.Parse(MetadataAuthoring.Call(root,"locate",System.Text.Json.JsonSerializer.Serialize(new{project=Path.Combine(root,"project.cpack"),manifest=locatorManifest,ids=requested})))!;
 string Status(string id)=>located["targets"]!.AsArray().Single(x=>x!["id"]!.ToString()==id)!["status"]!.ToString();
 if(Status("Any.Renamed::Value")!="registered"||Status("Any.Renamed::Absent")!="unregistered"||Status("Known::Good")!="registered"||Status("Known::Absent")!="unregistered"||Status("Broken::Thing")!="unavailable"||Status("Unknown::Thing")!="unregistered"||Status("bad-id")!="unavailable")throw new Exception("Locator tri-state confusion");
 int reads=0;RelationLocators.Query(locatorManifest,root,requested,path=>{reads++;if(Path.GetFileName(path)=="known.cpack")return knownManifest;if(Path.GetFileName(path)=="missing.cpack")throw new IOException();throw new Exception("Unrequested namespace opened");});if(reads!=2)throw new Exception("Not scoped/cached to requested manifests");
 var unknown=RelationLocators.Query("broken",root,new[]{"Known::Good"},_=>throw new Exception("Invalid manifest triggered read"));if(unknown["targets"]![0]!["status"]!.ToString()!="unavailable")throw new Exception("Invalid project treated as missing namespace");
 var mismatched=RelationLocators.Query(locatorManifest,root,new[]{"Known::Good"},_=>"pack Other version \"1\" {} ");if(mismatched["targets"]![0]!["status"]!.ToString()!="unavailable")throw new Exception("Mismatched registration accepted");
 string outsideManifest=root+"-external.cpack";try{
 File.WriteAllText(outsideManifest,knownManifest);string externalRegistration="project Any.Renamed version \"1\" { registry Known \"../"+Path.GetFileName(outsideManifest)+"\"; }";
 var scoped=JsonNode.Parse(MetadataAuthoring.Call(root,"locate",System.Text.Json.JsonSerializer.Serialize(new{project=Path.Combine(root,"project.cpack"),manifest=externalRegistration,ids=new[]{"Known::Good"}})))!;
 if(scoped["targets"]![0]!["status"]!.ToString()!="unavailable"||!scoped["targets"]![0]!["namespaceRegistered"]!.GetValue<bool>())throw new Exception("Locator scope broadened outside owned root");
 }finally{File.Delete(outsideManifest);}
 string effectiveManifest="project Meaning version \"1\" { standalone false; element Base object \"Base.celem\"; element Child object \"Child.celem\"; element Role module \"Role.celem\"; element Fn function \"Fn.celem\"; element Impl implementation \"Impl.celem\"; element Unused object \"Unreadable.celem\"; }";
 string child="object Meaning::Child extends Meaning::Base { value count = 0; value enabled = false; module Meaning::Role; }";
 File.WriteAllText(Path.Combine(root,"Base.celem"),"object Meaning::Base { value count = 5; value enabled = true; value inherited = \"parent\"; }");
 File.WriteAllText(Path.Combine(root,"Role.celem"),"module Meaning::Role { require Meaning::Fn () -> int; default Meaning::Fn with Meaning::Impl; }");File.WriteAllText(Path.Combine(root,"Fn.celem"),"function Meaning::Fn () -> int {}");File.WriteAllText(Path.Combine(root,"Impl.celem"),"implementation Meaning::Impl for Meaning::Fn () -> int { body common \"must-not-read.csbody\"; }");
 string effectiveRequest=System.Text.Json.JsonSerializer.Serialize(new{project=Path.Combine(root,"project.cpack"),manifest=effectiveManifest,id="Meaning::Child",text=child});
 var applied=JsonNode.Parse(MetadataAuthoring.Call(root,"effective",effectiveRequest))!;if(applied["status"]!.ToString()!="available"||applied["bodyReads"]!.GetValue<int>()!=0)throw new Exception(applied.ToJsonString());
 var effectiveValues=applied["values"]!.AsArray();if(effectiveValues.Single(v=>v!["field"]!.ToString()=="count")!["value"]!.GetValue<int>()!=0||effectiveValues.Single(v=>v!["field"]!.ToString()=="enabled")!["value"]!.GetValue<bool>()||effectiveValues.Single(v=>v!["field"]!.ToString()=="inherited")!["origin"]!.ToString()!="Meaning::Base")throw new Exception("Core inheritance/origin not preserved");
 if(applied["requirements"]![0]!["defaults"]![0]!["implementation"]!.ToString()!="Meaning::Impl"||applied["providerSelection"]!.ToString()!="not-performed"||applied["declarationsLoaded"]!.AsArray().Any(x=>x!.ToString()=="Meaning::Unused"))throw new Exception("Core module/declaration locality");
 var overlay=JsonNode.Parse(MetadataAuthoring.Call(root,"effective",System.Text.Json.JsonSerializer.Serialize(new{project=Path.Combine(root,"project.cpack"),manifest=effectiveManifest,id="Meaning::Child",text=child,drafts=new[]{new{id="Meaning::Base",text="object Meaning::Base { value inherited = \"draft-parent\"; }"}}})))!;if(overlay["values"]!.AsArray().Single(v=>v!["field"]!.ToString()=="inherited")!["value"]!.ToString()!="draft-parent")throw new Exception("Owned parent draft overlay omitted");
 var cycle=JsonNode.Parse(MetadataAuthoring.Call(root,"effective",System.Text.Json.JsonSerializer.Serialize(new{project=Path.Combine(root,"project.cpack"),manifest=effectiveManifest,id="Meaning::Child",text="object Meaning::Child extends Meaning::Child {}"})))!;if(cycle["status"]!.ToString()!="unavailable"||cycle["code"]!.ToString()!="INHERITANCE_CYCLE")throw new Exception("Core inheritance diagnostic replaced");
 string catalogRoot=Path.Combine(root,"catalog");Directory.CreateDirectory(catalogRoot);string catalogProject=Path.Combine(catalogRoot,"project.cpack"),catalogManifest="project Catalog version \"1\" { standalone false; registry Unused \"must-not-open.cpack\"; ";for(int n=0;n<40;n++)catalogManifest+="element Item"+n.ToString("D2")+" object \"Item"+n.ToString("D2")+".celem\"; ";File.WriteAllText(catalogProject,catalogManifest+"}");string selectedFile=Path.Combine(catalogRoot,"Item00.celem");File.WriteAllText(selectedFile,"object Catalog::Item00 { value text = \"old\"; }");
 var catalog=JsonNode.Parse(MetadataAuthoring.Call(root,"catalog",System.Text.Json.JsonSerializer.Serialize(new{project=catalogProject,request=new{action="list",kind="object"}})))!;if(catalog["total"]!.GetValue<int>()!=40||catalog["units"]!.AsArray().Count!=32||catalog["reads"]!["declarations"]!.GetValue<int>()!=0)throw new Exception("Catalog eager declaration scan");
 var catalogPage=JsonNode.Parse(MetadataAuthoring.Call(root,"catalog",System.Text.Json.JsonSerializer.Serialize(new{project=catalogProject,request=new{action="list",page=1}})))!;if(catalogPage["units"]!.AsArray().Count!=8||catalogPage["units"]![0]!["id"]!.ToString()!="Catalog::Item32")throw new Exception("Catalog page ordering");
 string catalogRead=System.Text.Json.JsonSerializer.Serialize(new{project=catalogProject,request=new{action="read",id="Catalog::Item00"}});var readOne=JsonNode.Parse(MetadataAuthoring.Call(root,"catalog",catalogRead))!;if(readOne["element"]!["values"]!["text"]!.ToString()!="old"||readOne["reads"]!["declarations"]!.GetValue<int>()!=1)throw new Exception("Specific declaration read scope");
 var warm=JsonNode.Parse(MetadataAuthoring.Call(root,"catalog",catalogRead))!;if(OperatingSystem.IsLinux()&&warm["reads"]!["declarations"]!.GetValue<int>()!=0)throw new Exception("Core cache not reused");DateTime stamp=File.GetLastWriteTimeUtc(selectedFile);File.WriteAllText(selectedFile,"object Catalog::Item00 { value text = \"new\"; }");File.SetLastWriteTimeUtc(selectedFile,stamp);var refreshed=JsonNode.Parse(MetadataAuthoring.Call(root,"catalog",catalogRead))!;if(refreshed["element"]!["values"]!["text"]!.ToString()!="new"||refreshed["element"]!["metadataVersion"]!.ToString()==readOne["element"]!["metadataVersion"]!.ToString())throw new Exception("Catalog cache stale after restored mtime");
 var outsideCatalog=JsonNode.Parse(MetadataAuthoring.Call(root,"catalog",System.Text.Json.JsonSerializer.Serialize(new{project=catalogProject,request=new{action="read",id="Foreign::Item00"}})))!;if(outsideCatalog["status"]!.ToString()!="unavailable")throw new Exception("Catalog auto-opened a foreign namespace");
 string modelRoot=Path.Combine(root,"schema-model");Directory.CreateDirectory(modelRoot);string modelProject=Path.Combine(modelRoot,"project.cpack");
 string modelManifest="project ViewModel version \"1\" { standalone false; target linux ViewModel::Target; target android ViewModel::Target; element Target buildtarget \"target.celem\"; element Shape schema \"Shape.celem\"; element Item object \"Item.celem\"; element Fn function \"Fn.celem\"; element Body implementation \"Body.celem\"; }";File.WriteAllText(modelProject,modelManifest);
 File.WriteAllText(Path.Combine(modelRoot,"Shape.celem"),"schema ViewModel::Shape { field callback single function ViewModel::Fn; field numbers multiple general int; }");File.WriteAllText(Path.Combine(modelRoot,"Fn.celem"),"function ViewModel::Fn (bool enabled,int[] nodes) -> string[] {}");File.WriteAllText(Path.Combine(modelRoot,"Body.celem"),"implementation ViewModel::Body for ViewModel::Fn (bool enabled,int[] nodes) -> string[] { body android \"missing-android-body.csbody\"; body common \"missing-common-body.csbody\"; }");
 string modelSource="object ViewModel::Item { use schema ViewModel::Shape; data callback = ViewModel::Body; data numbers = [0, 2]; }";File.WriteAllText(Path.Combine(modelRoot,"Item.celem"),modelSource);
 var nativeModel=JsonNode.Parse(MetadataAuthoring.Call(root,"effective",System.Text.Json.JsonSerializer.Serialize(new{project=modelProject,manifest=modelManifest,id="ViewModel::Item",text=modelSource,schemaView=true})))!;
 if(nativeModel["status"]!.ToString()!="available"||nativeModel["bodyReads"]!.GetValue<int>()!=0||nativeModel["schemaModel"]!["validation"]!["status"]!.ToString()!="valid"||nativeModel["schemaModel"]!["functions"]!["ViewModel::Fn"]!["args"]![1]!["type"]!.ToString()!="int[]"||nativeModel["schemaModel"]!["implementations"]!.AsObject().Single().Value!["targets"]!.AsArray().Count!=2)throw new Exception("Native schema/function model read bodies or lost typed contracts: "+nativeModel.ToJsonString());
 string modelEdited=System.Text.Json.JsonSerializer.Deserialize<string>(MetadataAuthoring.Call(root,"setDataPath",System.Text.Json.JsonSerializer.Serialize(new{text=modelSource,path=new object[]{"numbers",1},value=3})))!;if(!modelEdited.Contains("data numbers = [0, 3];",StringComparison.Ordinal)||!modelEdited.Contains("data callback = ViewModel::Body;",StringComparison.Ordinal))throw new Exception("Native explicit path edit lost sibling function association");
 Console.WriteLine("CATALOG:"+catalog.ToJsonString());
 Console.WriteLine("EFFECTIVE:"+applied.ToJsonString());
 Console.WriteLine("LOCATORS:"+located.ToJsonString());
 Console.WriteLine("RELATIONS:"+relationships.ToJsonString());
 Console.WriteLine("TYPED:"+typedRelations.ToJsonString());
 Console.WriteLine("Target metadata owned units/inspect/compiler refusal PASS");
 }finally{Directory.Delete(root,true);}
 """);
 var result=Processes.Run(new[]{Environment.GetEnvironmentVariable("CONFECTORY_DOTNET")??"dotnet","run","--project",Path.Combine(folder,"check.csproj"),"-c","Release"},timeoutSeconds:120);True(result.ExitCode==0,result.Stdout+result.Stderr);True(result.Stdout.Contains("Target metadata owned units/inspect/compiler refusal PASS",StringComparison.Ordinal),result.Stdout+result.Stderr);
 string typedSource="implementation Any.Renamed::Work for Missing::Own () -> int { use schema Missing::Shape; contain object Missing::Child; import Missing::Fn as A (string,int[]) -> bool in Missing::Scope; import Missing::Fn as B (string,int[]) -> bool; body common \"must-not-read.csbody\"; }";
 var typedDesktop=Processes.Run(new[]{Processes.DotNet(),Path.Combine(Fixture.Repo,"targets","element-authoring","bin","Release","net10.0","Confectory.ElementAuthoring.dll")},input:System.Text.Json.JsonSerializer.Serialize(new{operation="inspect",text=typedSource}),timeoutSeconds:30);var typedExpected=System.Text.Json.Nodes.JsonNode.Parse(typedDesktop.Stdout)!;True(typedExpected["ok"]!.GetValue<bool>(),typedDesktop.Stdout);var targetTyped=System.Text.Json.Nodes.JsonNode.Parse(result.Stdout.Split('\n').Single(line=>line.StartsWith("TYPED:",StringComparison.Ordinal))[6..]);True(System.Text.Json.Nodes.JsonNode.DeepEquals(typedExpected["result"]!["relations"],targetTyped),"Declared typed reference replies differ");
 var desktop=Processes.Run(new[]{Processes.DotNet(),Path.Combine(Fixture.Repo,"targets","element-authoring","bin","Release","net10.0","Confectory.ElementAuthoring.dll")},input:System.Text.Json.JsonSerializer.Serialize(new{operation="inspect",text="module Any.Renamed::Rules extends Missing::Parent { module Missing::Role; include Missing::Child; require Missing::Function (int) -> int; default Missing::Function with Missing::Body; provide Missing::Function with Missing::Explicit; }"}),timeoutSeconds:30);
 var expected=System.Text.Json.Nodes.JsonNode.Parse(desktop.Stdout)!;True(expected["ok"]!.GetValue<bool>(),desktop.Stdout);var targetRelations=System.Text.Json.Nodes.JsonNode.Parse(result.Stdout.Split('\n').Single(line=>line.StartsWith("RELATIONS:",StringComparison.Ordinal))[10..]);True(System.Text.Json.Nodes.JsonNode.DeepEquals(expected["result"]!["relations"],targetRelations),"Target relation replies differ");
 File.WriteAllText(Path.Combine(folder,"known.cpack"),"pack Known version \"0.1.0\" { element Good module \"not-opened.celem\"; }");
 var locatedDesktop=Processes.Run(new[]{Processes.DotNet(),Path.Combine(Fixture.Repo,"targets","element-authoring","bin","Release","net10.0","Confectory.ElementAuthoring.dll")},input:System.Text.Json.JsonSerializer.Serialize(new{operation="locate",project=Path.Combine(folder,"project.cpack"),manifest="project Any.Renamed version \"0.1.0\" { registry Known \"known.cpack\"; registry Broken \"missing.cpack\"; registry Unused \"must-not-read.cpack\"; element Value object \"not-read.celem\"; }",ids=new[]{"Any.Renamed::Value","Any.Renamed::Absent","Known::Good","Known::Absent","Broken::Thing","Unknown::Thing","bad-id"}}),timeoutSeconds:30);
 var locatorReply=System.Text.Json.Nodes.JsonNode.Parse(locatedDesktop.Stdout)!;True(locatorReply["ok"]!.GetValue<bool>(),locatedDesktop.Stdout);var targetLocators=System.Text.Json.Nodes.JsonNode.Parse(result.Stdout.Split('\n').Single(line=>line.StartsWith("LOCATORS:",StringComparison.Ordinal))[9..]);True(System.Text.Json.Nodes.JsonNode.DeepEquals(locatorReply["result"],targetLocators),"Locator replies differ");
 foreach(string name in new[]{"Base","Role","Fn","Impl"})File.WriteAllText(Path.Combine(folder,name+".celem"),name switch{"Base"=>"object Meaning::Base { value count = 5; value enabled = true; value inherited = \"parent\"; }","Role"=>"module Meaning::Role { require Meaning::Fn () -> int; default Meaning::Fn with Meaning::Impl; }","Fn"=>"function Meaning::Fn () -> int {}",_=>"implementation Meaning::Impl for Meaning::Fn () -> int { body common \"must-not-read.csbody\"; }"});
 var appliedDesktop=Processes.Run(new[]{Processes.DotNet(),Path.Combine(Fixture.Repo,"targets","element-authoring","bin","Release","net10.0","Confectory.ElementAuthoring.dll")},input:System.Text.Json.JsonSerializer.Serialize(new{operation="effective",project=Path.Combine(folder,"project.cpack"),manifest="project Meaning version \"1\" { standalone false; element Base object \"Base.celem\"; element Child object \"Child.celem\"; element Role module \"Role.celem\"; element Fn function \"Fn.celem\"; element Impl implementation \"Impl.celem\"; element Unused object \"Unreadable.celem\"; }",id="Meaning::Child",text="object Meaning::Child extends Meaning::Base { value count = 0; value enabled = false; module Meaning::Role; }"}),timeoutSeconds:30);
 var effectiveReply=System.Text.Json.Nodes.JsonNode.Parse(appliedDesktop.Stdout)!;True(effectiveReply["ok"]!.GetValue<bool>(),appliedDesktop.Stdout);var targetEffective=System.Text.Json.Nodes.JsonNode.Parse(result.Stdout.Split('\n').Single(line=>line.StartsWith("EFFECTIVE:",StringComparison.Ordinal))[10..]);True(System.Text.Json.Nodes.JsonNode.DeepEquals(effectiveReply["result"],targetEffective),"Effective metadata providers differ");
 string catalogManifest="project Catalog version \"1\" { standalone false; registry Unused \"must-not-open.cpack\"; ";for(int n=0;n<40;n++)catalogManifest+="element Item"+n.ToString("D2")+" object \"Item"+n.ToString("D2")+".celem\"; ";string catalogProject=Path.Combine(folder,"catalog.cpack");File.WriteAllText(catalogProject,catalogManifest+"}");
 var catalogDesktop=Processes.Run(new[]{Processes.DotNet(),Path.Combine(Fixture.Repo,"targets","element-authoring","bin","Release","net10.0","Confectory.ElementAuthoring.dll")},input:System.Text.Json.JsonSerializer.Serialize(new{operation="catalog",project=catalogProject,request=new{action="list",kind="object"}}),timeoutSeconds:30);var catalogue=System.Text.Json.Nodes.JsonNode.Parse(catalogDesktop.Stdout)!;True(catalogue["ok"]!.GetValue<bool>(),catalogDesktop.Stdout);var targetCatalog=System.Text.Json.Nodes.JsonNode.Parse(result.Stdout.Split('\n').Single(line=>line.StartsWith("CATALOG:",StringComparison.Ordinal))[8..])!;catalogue["result"]!.AsObject().Remove("metadataVersion");targetCatalog.AsObject().Remove("metadataVersion");catalogue["result"]!.AsObject().Remove("reads");targetCatalog.AsObject().Remove("reads");True(System.Text.Json.Nodes.JsonNode.DeepEquals(catalogue["result"],targetCatalog),"Catalog domain reply differs");




 }
 public void test_development_tools_owned_scope_shared_draft_no_confirm_and_locality()
 {
  string sample=Path.Combine(f.Root,"development-tools-consumer");Fixture.CopyTree(Path.Combine(Fixture.Repo,"examples","edit-workspace"),sample);
  foreach(string name in new[]{"file-stream","schema-editing","edit-workspace","save","change-set","pack-workspace","development-tools"})Fixture.CopyTree(Path.Combine(Fixture.Repo,"packs",name),Path.Combine(f.Root,"packs",name));
  string project=Path.Combine(sample,"project.cpack");File.WriteAllText(project,File.ReadAllText(project).Replace("../../packs/","../packs/").Replace("../../targets/dotnet/pack.cpack","../target/pack.cpack").Replace("element Main function","registry Confectory.PackWorkspace \"../packs/pack-workspace/pack.cpack\"; dependency Confectory.PackWorkspace version \"0.1.0\";\nregistry Confectory.DevelopmentTools \"../packs/development-tools/pack.cpack\"; dependency Confectory.DevelopmentTools version \"0.1.0\";\nelement Main function"));
  f.Add("App","object","ToolObject","object App::ToolObject {value count = 0;}");f.Sync();
  string originMain=Path.Combine(sample,"Main.celem");if(!File.Exists(originMain))originMain=Path.Combine(sample,"main.celem");var originSource=File.ReadAllText(originMain);int originEnd=originSource.LastIndexOf('}');File.WriteAllText(originMain,originSource.Insert(originEnd,"provide Confectory.DevelopmentTools::BindOrigin with Confectory.DevelopmentTools::BindOriginBody;\nprovide Confectory.FileStream::BrowseDirectory with Confectory.FileStream::BrowseDirectoryBody;\n"));
  File.WriteAllText(Path.Combine(sample,"main_body.celem"),"""
  implementation Example.EditWorkspace::MainBody for Example.EditWorkspace::Main () -> int {
  import Confectory.DevelopmentTools::Open as ToolsOpen (string,string,string,string,string) -> string;
  import Confectory.DevelopmentTools::Invoke as Tool (string,string,string,string) -> string;
  import Confectory.DevelopmentTools::BindOrigin as BindOrigin (string,string,string,string) -> void;
  import Confectory.DevelopmentTools::Definitions as Definitions (string) -> string;
  import Confectory.DevelopmentTools::Snapshot as ToolsSnapshot (string) -> string;
  import Confectory.DevelopmentTools::Close as ToolsClose (string) -> void;
  import Confectory.PackWorkspace::Open as Open (string,string,string) -> string;
  import Confectory.PackWorkspace::Command as Command (string,string,string) -> string;
  import Confectory.PackWorkspace::Snapshot as Snapshot (string) -> string;
  import Confectory.PackWorkspace::Close as Close (string) -> void;
  body common "main.csbody";}
  """);
  File.WriteAllText(Path.Combine(sample,"main.csbody"),"""
  string project=Environment.GetEnvironmentVariable("CONFECTORY_TEST_AUTHOR_PROJECT")!;string view=calls.Open.Invoke(project,"alice","editor"),capability=calls.ToolsOpen.Invoke(project,"project-A","App","alice","editor");
  void Check(bool value,string reason){if(!value)throw new Exception(reason);}
  bool Denied(Action action){try{action();return false;}catch(UnauthorizedAccessException){return true;}catch(InvalidOperationException){return true;}}
  string Request(string id,string text="",long revision=0)=>new System.Text.Json.Nodes.JsonObject{["projectId"]="project-A",["id"]=id,["text"]=text,["expectedRevision"]=revision}.ToJsonString();
  try{
   calls.BindOrigin.Invoke(capability,"task-A","worker-A","request-A");
   Check(calls.Definitions.Invoke(capability).Contains("project-A")&&!calls.Definitions.Invoke(capability).Contains("confirm"),"bounded tool definitions expose only granted project operations");string final=System.IO.File.ReadAllText(project);calls.Command.Invoke(view,"select","{\"id\":\"App::ToolObject\"}");
   var read=System.Text.Json.Nodes.JsonNode.Parse(calls.Tool.Invoke(capability,"read","workspace_read",Request("App::ToolObject")))!;long revision=read["revision"]!.GetValue<long>();
   string edited="object App::ToolObject {value count = 2;}";string args=Request("App::ToolObject",edited,revision);var changed=System.Text.Json.Nodes.JsonNode.Parse(calls.Tool.Invoke(capability,"stage","workspace_stage",args))!;Check(changed["applied"]!.GetValue<bool>(),"tool CAS edit");
   var human=System.Text.Json.Nodes.JsonNode.Parse(calls.Snapshot.Invoke(view))!;var origin=System.Text.Json.Nodes.JsonNode.Parse(calls.ToolsSnapshot.Invoke(capability))!["dirty"]!["App::ToolObject"]!["origins"]![0]!;Check(origin["task"]!.ToString()=="task-A"&&origin["worker"]!.ToString()=="worker-A"&&origin["projectId"]!.ToString()=="project-A"&&origin["matchesCurrentHash"]!.GetValue<bool>(),"trusted per-Worker applied contribution matches exact draft");Check(human["unit"]!["text"]!.ToString()==edited&&human["selected"]!.ToString()=="App::ToolObject","same draft without stealing UI selection");
   var stale=System.Text.Json.Nodes.JsonNode.Parse(calls.Tool.Invoke(capability,"stale","workspace_stage",Request("App::ToolObject","object App::ToolObject {value count = 3;}",revision)))!;Check(stale["conflict"]!.GetValue<bool>(),"stale revision rejected");
   calls.Command.Invoke(view,"edit",new System.Text.Json.Nodes.JsonObject{["expectedRevision"]=revision+1,["text"]="object App::ToolObject {value count = 4;}"}.ToJsonString());calls.Tool.Invoke(capability,"stage","workspace_stage",args);Check(System.Text.Json.Nodes.JsonNode.Parse(calls.Snapshot.Invoke(view))!["unit"]!["text"]!.ToString().Contains("4"),"duplicate call does not replay stage");
   Check(Denied(()=>calls.Tool.Invoke(capability,"other-project","workspace_read",Request("App::ToolObject").Replace("project-A","project-B"))),"project isolation");Check(Denied(()=>calls.Tool.Invoke(capability,"foreign","workspace_read",Request("Other::Secret"))),"namespace isolation");
   Check(Denied(()=>calls.Tool.Invoke(capability,"confirm","confirm",Request("App::ToolObject"))),"no automatic Confirm");Check(Denied(()=>calls.Tool.Invoke(capability,"execute","shell",Request("App::ToolObject"))),"no process authority");
   calls.Tool.Invoke(capability,"create","workspace_create","{\"projectId\":\"project-A\",\"id\":\"App::ToolCreated\",\"kind\":\"object\"}");Check(System.IO.File.ReadAllText(project)==final,"creation must not write final registration");var snapshot=System.Text.Json.Nodes.JsonNode.Parse(calls.ToolsSnapshot.Invoke(capability))!;Check(snapshot["staged"]!["App::ToolCreated"] is not null&&snapshot["staged"]!["App::ProjectManifest"] is not null,"explicit manifest registration included in staged scope");Check(snapshot["dirty"]!["App::ToolCreated"]!["origins"]![0]!["operation"]!.ToString()=="workspace_create"&&!snapshot["dirty"]!["App::ToolCreated"]!["origins"]![0]!["matchesCurrentHash"]!.GetValue<bool>(),"creation provenance is distinguished from exclusive current content authorship");
   calls.ToolsClose.Invoke(capability);Check(Denied(()=>calls.Tool.Invoke(capability,"closed","workspace_read",Request("App::ToolObject"))),"closed capability rejects calls");Check(System.Text.Json.Nodes.JsonNode.Parse(calls.Snapshot.Invoke(view))!["unit"]!["text"]!.ToString().Contains("4"),"closing tools preserves borrowed UI draft");
   capability=calls.ToolsOpen.Invoke(project,"project-A","App","alice","editor");var restored=System.Text.Json.Nodes.JsonNode.Parse(calls.ToolsSnapshot.Invoke(capability))!;Check(restored["dirty"]!["App::ToolObject"]?["revision"]?.GetValue<long>()==revision+2&&restored["dirty"]!["App::ToolCreated"] is not null&&restored["dirty"]!["App::ProjectManifest"] is not null,"fresh capability snapshots actual retained project draft revisions");Check(restored["staged"]!.AsObject().Count==0&&restored["log"]!.AsArray().Count==0&&System.IO.File.ReadAllText(project)==final,"snapshot restoration does not replay tools or confirm sources");
   Check(restored["dirty"]!["App::ToolObject"]!["origins"]![0]!["task"]!.ToString()=="task-A"&&!restored["dirty"]!["App::ToolObject"]!["origins"]![0]!["matchesCurrentHash"]!.GetValue<bool>(),"durable contribution survives owner replacement and does not claim later human edit");Check(Denied(()=>calls.BindOrigin.Invoke(capability,"task-B","worker-B","request-B"))==false,"unused fresh capability can bind its own new origin");bool bad=false;try{calls.Tool.Invoke(capability,"uncertain","workspace_stage",Request("App::ToolObject","invalid source",revision+2));}catch(ArgumentException){bad=true;}catch(InvalidOperationException){bad=true;}Check(bad&&Denied(()=>calls.Tool.Invoke(capability,"uncertain","workspace_stage",Request("App::ToolObject","object App::ToolObject {value count = 5;}",revision+2))),"uncertain mutation is not replayed even with repaired input");var uncertain=System.Text.Json.Nodes.JsonNode.Parse(calls.ToolsSnapshot.Invoke(capability))!;Check(System.Linq.Enumerable.Any(uncertain["provenance"]!.AsArray(),x=>x!["callId"]?.ToString()=="uncertain"&&x["state"]?.ToString()=="outcome-unknown")&&System.Text.Json.Nodes.JsonNode.Parse(calls.Snapshot.Invoke(view))!["unit"]!["text"]!.ToString().Contains("4"),"unknown outcome remains explicit, no guessed change");calls.Tool.Invoke(capability,"unchanged","workspace_stage",Request("App::ToolObject","object App::ToolObject {value count = 4;}",revision+2));var noOp=System.Text.Json.Nodes.JsonNode.Parse(calls.ToolsSnapshot.Invoke(capability))!;Check(noOp["dirty"]!["App::ToolObject"]!["attribution"]!.ToString()=="unknown-current-author"&&System.Linq.Enumerable.Any(noOp["provenance"]!.AsArray(),x=>x!["callId"]?.ToString()=="unchanged"&&x["state"]?.ToString()=="unchanged"),"no-op tool cannot claim a human-authored draft");Check(Denied(()=>calls.BindOrigin.Invoke(capability,"spoof","spoof","spoof")),"bound origin immutable");string foreign=calls.ToolsOpen.Invoke(project,"project-B","App","alice","editor");try{Check(System.Text.Json.Nodes.JsonNode.Parse(calls.ToolsSnapshot.Invoke(foreign))!["provenance"]!.AsArray().Count==0,"cross-project journal is not attributed or exposed");}finally{calls.ToolsClose.Invoke(foreign);}Console.WriteLine("Development tools scope/shared draft/CAS/dedup/no Confirm/cleanup PASS");return 0;
  }finally{calls.ToolsClose.Invoke(capability);calls.Close.Invoke(view);}
  """);
  string? host=Environment.GetEnvironmentVariable("CONFECTORY_ELEMENT_AUTHORING_HOST"),selected=Environment.GetEnvironmentVariable("CONFECTORY_TEST_AUTHOR_PROJECT");
  try{Environment.SetEnvironmentVariable("CONFECTORY_ELEMENT_AUTHORING_HOST",Path.Combine(Fixture.Repo,"targets","element-authoring","bin","Release","net10.0","Confectory.ElementAuthoring.dll"));Environment.SetEnvironmentVariable("CONFECTORY_TEST_AUTHOR_PROJECT",f.Project);var built=new Builder(project,"portable").Build();True(!Strings(built,"includedPacks").Contains("Confectory.Agent"));Output(built,"Development tools scope/shared draft/CAS/dedup/no Confirm/cleanup PASS");File.AppendAllText(Path.Combine(f.Root,"packs","development-tools","Invoke.csbody"),"\n// development tool provider locality\n");var changed=new Builder(project,"portable").Build();PackRebuilt(changed,new[]{"Confectory.DevelopmentTools::InvokeBody"});Equal(0,Strings(changed,"statistics","compiledContracts").Length);File.AppendAllText(Path.Combine(f.Root,"packs","development-tools","Snapshot.csbody"),"\n// retained draft snapshot locality\n");var snapshotChange=new Builder(project,"portable").Build();PackRebuilt(snapshotChange,new[]{"Confectory.DevelopmentTools::SnapshotBody"});Equal(0,Strings(snapshotChange,"statistics","compiledContracts").Length);}
  finally{Environment.SetEnvironmentVariable("CONFECTORY_ELEMENT_AUTHORING_HOST",host);Environment.SetEnvironmentVariable("CONFECTORY_TEST_AUTHOR_PROJECT",selected);}
 }
}
