using System.Security.Cryptography;
using System.Text;
using System.Text.Json.Nodes;
using Confectory.Core;
namespace Confectory.Tests;
public sealed class ProjectionDeliveryTests : TestCase
{
 public void test_source_free_durable_large_function_bounds_versions_drafts_and_batches()
 {
  string root=Path.Combine(f.Root,"projection consumer"),project=Path.Combine(root,"project.cpack");Fixture.CopyTree(Path.Combine(Fixture.Repo,"examples","projects","authoring"),root);File.WriteAllText(project,File.ReadAllText(project).Replace("../../../targets/",Path.Combine(Fixture.Repo,"targets")+"/",StringComparison.Ordinal));string function="Example.Authoring::Main",implementation="Example.Authoring::MainBody",target=implementation+"/body:common",host=Path.Combine(Fixture.Repo,"targets","element-authoring","bin","Release","net10.0","Confectory.ElementAuthoring.dll");
  JsonNode Call(string operation,JsonObject args){args["operation"]=operation;var run=Processes.Run([Processes.DotNet(),host],args.ToJsonString(),timeoutSeconds:60);var reply=JsonNode.Parse(run.Stdout)!;True(reply["ok"]!.GetValue<bool>(),run.Stdout+run.Stderr);return reply["result"]??reply["reply"]!;}
  JsonObject Identity()=>new(){["project"]=project,["function"]=function,["implementation"]=implementation,["target"]=target};
  string Hash(string path)=>Convert.ToHexString(SHA256.HashData(File.ReadAllBytes(path))).ToLowerInvariant();
  JsonObject Hashes()=>new(){["contract"]=Hash(Path.Combine(root,"main.celem")),["implementation"]=Hash(Path.Combine(root,"main_body.celem")),["body"]=Hash(Path.Combine(root,"main.csbody"))};
  JsonNode Generate(string? text=null)=>Call("algorithmProject",new(){["contract"]=File.ReadAllText(Path.Combine(root,"main.celem")),["implementation"]=File.ReadAllText(Path.Combine(root,"main_body.celem")),["body"]=text??File.ReadAllText(Path.Combine(root,"main.csbody"))});
  JsonNode Publish(JsonNode artifact,long version,string channel="confirmed",string participant="A"){var args=Identity();args["artifact"]=artifact.DeepClone();args["sourceHashes"]=Hashes();args["expectedVersion"]=version;args["channel"]=channel;args["participant"]=participant;args["context"]="one";return Call("projectionPublish",args);}
  JsonNode Query(string channel="confirmed",string participant="A"){var args=Identity();args["channel"]=channel;args["participant"]=participant;args["context"]="one";return Call("projectionQuery",args);}
  JsonNode Browse(JsonObject options){var args=Identity();args["options"]=options;return Call("projectionBrowse",args);}
  JsonNode Delta(long baseline,long next,JsonObject? options=null){var args=Identity();args["baseVersion"]=baseline;args["newVersion"]=next;args["options"]=options??new JsonObject();return Call("projectionDelta",args);}
  string body="string privateSentinel=\"PRIVATE_IMPLEMENTATION_MARKER\";\n"+string.Join("\n",Enumerable.Range(0,900).Select(n=>$"if (true) {{ Console.WriteLine(\"secret literal {n}\"); }}"))+"\nreturn 0;";File.WriteAllText(Path.Combine(root,"main.csbody"),body);var artifact=Generate();True(Publish(artifact,0)["accepted"]!.GetValue<bool>());var full=Query();Equal("current-source",full["freshness"]!.ToString());True(!full["behaviorValidated"]!.GetValue<bool>());True(!full.ToJsonString().Contains("privateSentinel",StringComparison.Ordinal));True(!full.ToJsonString().Contains("secret literal",StringComparison.Ordinal));var baseline=Browse(new());Equal(1,baseline["nodes"]!.AsArray().Count);True(Encoding.UTF8.GetByteCount(baseline.ToJsonString())<32768);
  var page=Browse(new(){["pageSize"]=3,["depth"]=1,["nodeLimit"]=4});Equal(4,page["nodes"]!.AsArray().Count);True(page["truncated"]!.GetValue<bool>());Equal(3,page["nodes"]![0]!["nextOffset"]!.GetValue<int>());string child=page["nodes"]![0]!["childIDs"]![0]!.ToString();var nextPage=Browse(new(){["pageSize"]=3,["offset"]=3});True(!JsonNode.DeepEquals(page["nodes"]![0]!["childIDs"],nextPage["nodes"]![0]!["childIDs"]));Equal(child,Browse(new(){["nodeID"]=child})["nodes"]![0]!["nodeID"]!.ToString());
  string contractPath=Path.Combine(root,"main.celem");File.WriteAllText(contractPath,File.ReadAllText(contractPath).Replace(" {"," { description \"public editor description\";",StringComparison.Ordinal));artifact=Generate();True(Publish(artifact,1)["accepted"]!.GetValue<bool>());var delta=Delta(1,2);Equal("delta",delta["status"]!.ToString());Equal(baseline["viewHash"]!.ToString(),delta["baseViewHash"]!.ToString());Equal(baseline["rootID"]!.ToString(),delta["snapshot"]!["rootID"]!.ToString());True(!Publish(artifact,1)["accepted"]!.GetValue<bool>());True(Delta(88,2)["requiresRefresh"]!.GetValue<bool>());True(Delta(1,1)["requiresRefresh"]!.GetValue<bool>());
  var draft=Generate(body+"\n// local draft");Equal("draft-cannot-publish-to-confirmed-channel",Publish(draft,2)["reason"]!.ToString());True(Publish(draft,0,"draft")["accepted"]!.GetValue<bool>());Equal(2L,Query()["version"]!.GetValue<long>());Equal("draft-unconfirmed",Query("draft")["freshness"]!.ToString());Equal("missing",Query("draft","B")["status"]!.ToString());File.WriteAllText(Path.Combine(root,"main.csbody"),body+"\n// source changed");Equal("stale",Query()["status"]!.ToString());True(Delta(1,2)["requiresRefresh"]!.GetValue<bool>());True(Publish(Generate(),2)["accepted"]!.GetValue<bool>());Equal("node-identity-retired",Delta(2,3,new(){["nodeID"]=child})["status"]!.ToString());
  var affected=Call("projectionAffected",new(){["project"]=project,["changedIDs"]=new JsonArray(target,"Other::Missing")});Equal("Other::Missing",affected["unknownIDs"]![0]!.ToString());
  JsonNode Queue(string action,JsonNode? request=null,string? id=null)=>Call("projectionQueue",new(){["project"]=project,["participant"]="A",["context"]="one",["action"]=action,["request"]=request?.DeepClone(),["requestID"]=id});var item=new JsonObject{["function"]=function,["implementation"]=implementation,["bodyID"]=target,["origin"]="human",["changeKind"]="functional",["batch"]="first"};Queue("notify",item);string first=Queue("list")[0]!["requestID"]!.ToString();item["batch"]="second";Queue("notify",item);Queue("ack",id:first);Equal(1,Queue("list").AsArray().Count);item["origin"]="ai";Queue("notify",item);Equal(0,Queue("list").AsArray().Count);
  string providerPath=Path.Combine(root,"main_body.celem"),linuxPath=Path.Combine(root,"main-linux.csbody");File.WriteAllText(providerPath,File.ReadAllText(providerPath).Replace("body common", "body linux \"main-linux.csbody\"; body common",StringComparison.Ordinal));File.WriteAllText(linuxPath,File.ReadAllText(Path.Combine(root,"main.csbody")));var variant=Generate();var variantArgs=Identity();variantArgs["target"]=implementation+"/body:linux";variantArgs["artifact"]=variant.DeepClone();variantArgs["sourceHashes"]=Hashes();variantArgs["sourceHashes"]!["body"]=Hash(linuxPath);variantArgs["expectedVersion"]=0;True(Call("projectionPublish",variantArgs)["accepted"]!.GetValue<bool>());True(Publish(variant,3)["accepted"]!.GetValue<bool>());var variants=Call("projectionList",new(){["project"]=project,["function"]=function});Equal(2,variants.AsArray().Count);var onlyLinux=Call("projectionAffected",new(){["project"]=project,["changedIDs"]=new JsonArray(implementation+"/body:linux")});Equal(1,onlyLinux["affected"]!.AsArray().Count);Equal(implementation+"/body:linux",onlyLinux["affected"]![0]!["bodyID"]!.ToString());
  string schemaPath=Path.Combine(root,"function-schema.celem");File.WriteAllText(schemaPath,"function Example.Authoring::FunctionSchema () -> int { value editorTags = \"function,flow\"; value editorHelpFlow = \"Public syntax help, behavior requires review\"; }");File.WriteAllText(project,File.ReadAllText(project).Replace("element Main function", "element FunctionSchema function \"function-schema.celem\"; element Main function",StringComparison.Ordinal));File.WriteAllText(contractPath,File.ReadAllText(contractPath).Replace(" -> int {"," -> int extends Example.Authoring::FunctionSchema {",StringComparison.Ordinal));True(Publish(Generate(),4)["accepted"]!.GetValue<bool>());var editor=Call("editorDescribe",new(){["project"]=project,["element"]=function});Equal("Example.Authoring::FunctionSchema",editor["schemaOrigins"]!["editorHelpFlow"]!["schema"]!.ToString());True(Query()["editor"]!["help"]!["editorHelpFlow"]!.ToString().Contains("Public syntax help",StringComparison.Ordinal));File.AppendAllText(schemaPath,"\n// inherited public help revision changed\n");Equal("stale",Query()["status"]!.ToString());var schemaAffected=Call("projectionAffected",new(){["project"]=project,["changedIDs"]=new JsonArray("Example.Authoring::FunctionSchema")});Equal(1,schemaAffected["affected"]!.AsArray().Count);Equal(0,schemaAffected["unknownIDs"]!.AsArray().Count);
  Console.WriteLine("PROJECTION_METRICS "+new JsonObject{["analysis"]=full["analysisMetrics"]!.DeepClone(),["fullUtf8Bytes"]=Encoding.UTF8.GetByteCount(full.ToJsonString()),["rootUtf8Bytes"]=Encoding.UTF8.GetByteCount(baseline.ToJsonString()),["deltaUtf8Bytes"]=Encoding.UTF8.GetByteCount(delta.ToJsonString()),["freshConsumer"]="fresh OS host process per operation; no fresh AI reasoning context"}.ToJsonString());
 }
 public void test_pack_consumer_changed_ids_chief_routing_recovery_and_locality()
 {
  string consumer=Path.Combine(f.Root,"projection-consumer"),source=Path.Combine(f.Root,"projection-source"),owned=Path.Combine(f.Root,"projection-pack");Fixture.CopyTree(Path.Combine(Fixture.Repo,"examples","projection-maintenance"),consumer);Fixture.CopyTree(Path.Combine(Fixture.Repo,"examples","projects","authoring"),source);Fixture.CopyTree(Path.Combine(Fixture.Repo,"packs","algorithm-projection"),owned);string project=Path.Combine(consumer,"project.cpack"),sourceProject=Path.Combine(source,"project.cpack");File.WriteAllText(project,File.ReadAllText(project).Replace("../../",Fixture.Repo+"/",StringComparison.Ordinal).Replace(Path.Combine(Fixture.Repo,"packs","algorithm-projection","pack.cpack"),Path.Combine(owned,"pack.cpack"),StringComparison.Ordinal));File.WriteAllText(sourceProject,File.ReadAllText(sourceProject).Replace("../../../targets/",Fixture.Repo+"/targets/",StringComparison.Ordinal));string? saved=Environment.GetEnvironmentVariable("CONFECTORY_PROJECTION_PROJECT"),directory=Environment.GetEnvironmentVariable("CONFECTORY_PROJECTION_DIR"),host=Environment.GetEnvironmentVariable("CONFECTORY_ELEMENT_AUTHORING_HOST");try{Environment.SetEnvironmentVariable("CONFECTORY_PROJECTION_PROJECT",sourceProject);Environment.SetEnvironmentVariable("CONFECTORY_PROJECTION_DIR",Path.Combine(f.Root,"projection-storage"));Environment.SetEnvironmentVariable("CONFECTORY_ELEMENT_AUTHORING_HOST",Path.Combine(Fixture.Repo,"targets","element-authoring","bin","Release","net10.0","Confectory.ElementAuthoring.dll"));var built=new Builder(project,"linux").Build();var run=Processes.Run(Strings(built,"run"),timeoutSeconds:120);True(run.ExitCode==0,run.Stdout+run.Stderr);True(run.Stdout.Contains("chief Task routing",StringComparison.Ordinal));True(run.Stdout.Contains("Projection owner cleanup complete",StringComparison.Ordinal));File.AppendAllText(Path.Combine(owned,"Browse.csbody"),"\n// owning projection implementation locality probe\n");var changed=new Builder(project,"linux").Build();PackRebuilt(changed, new[]{"Confectory.AlgorithmProjection::BrowseBody"});Equal(0,Strings(changed,"statistics","compiledContracts").Length);File.WriteAllText(Path.Combine(owned,"Browse.celem"),File.ReadAllText(Path.Combine(owned,"Browse.celem")).Replace("Read bounded confirmed-source root","Inspect bounded confirmed-source root",StringComparison.Ordinal));var metadata=new Builder(project,"linux").Build();Equal(0,Strings(metadata,"statistics","compiledImplementations").Length);Equal(0,Strings(metadata,"statistics","compiledContracts").Length);}finally{Environment.SetEnvironmentVariable("CONFECTORY_PROJECTION_PROJECT",saved);Environment.SetEnvironmentVariable("CONFECTORY_PROJECTION_DIR",directory);Environment.SetEnvironmentVariable("CONFECTORY_ELEMENT_AUTHORING_HOST",host);}
 }

}
