#!/usr/bin/env python3
"""Public configurable completion policy locality and default-refusal check; no live AI."""
import pathlib,json,subprocess,tempfile,shutil,os
repo=pathlib.Path(__file__).resolve().parents[2];p=pathlib.Path(tempfile.mkdtemp(prefix='confectory-verification-policy-'));shutil.copytree(repo/'examples/supervision',p/'consumer',ignore=shutil.ignore_patterns('.confectory'));p=p/'consumer';manifest=p/'project.cpack';text=manifest.read_text()
for pack in ['agent','helper','worker-tasks','file-stream']:text=text.replace('../../packs/'+pack+'/pack.cpack',str(repo/'packs'/pack/'pack.cpack'))
text=text.replace('../../targets/dotnet/pack.cpack',str(repo/'targets/dotnet/pack.cpack'));manifest.write_text(text)
env=dict(os.environ);dotnet=env.get('CONFECTORY_DOTNET') or shutil.which('dotnet');assert dotnet, 'Set CONFECTORY_DOTNET to the installed .NET SDK executable';env['CONFECTORY_DOTNET']=dotnet;env.setdefault('DOTNET_CLI_HOME',str(p.parent/'dotnet-home'));cli=[env['CONFECTORY_DOTNET'],str(repo/'src/Confectory.Cli/bin/Release/net10.0/Confectory.Cli.dll'),'build',str(manifest),'portable']
def build():
 r=subprocess.run(cli,capture_output=True,text=True,env=env,timeout=180);assert r.returncode==0,r.stderr;return json.loads(r.stdout)
a=build();f=p/'Verifier.csbody';f.write_text(f.read_text()+'\n// verification policy body-only locality\n');b=build();assert b['statistics']['compiledImplementations']==['Example.Supervision::Verifier'];assert b['statistics']['compiledContracts']==[];print('PASS selected VerifyCompletion policy body compiles one implementation and zero contracts',flush=True)
f=p/'Main.celem';f.write_text(f.read_text().replace('with Example.Supervision::Verifier;','with Confectory.WorkerTasks::VerifyCompletionBody;'))
f=p/'MainBody.csbody';f.write_text('''string directory=System.IO.Path.Combine(System.IO.Path.GetTempPath(),"default-verification-"+Guid.NewGuid().ToString("N"));System.IO.Directory.CreateDirectory(directory);string helpers=calls.HelperOpen.Invoke(directory);string template="{\\"helper\\":\\"chief\\",\\"owner\\":\\"alice\\",\\"personality\\":\\"calm\\",\\"speciality\\":\\"tests\\"}";calls.HelperRecruit.Invoke(helpers,"alice",template);string session=calls.WorkerTasksOpen.Invoke(directory,"test-project",helpers,"alice","chief");string agent=calls.AgentOpen.Invoke("{\\"provider\\":\\"simulated\\",\\"model\\":\\"fake\\"}");try{calls.WorkerTasksAssign.Invoke(session,"chief",0,"assign","chief","task","{\\"goal\\":\\"marker\\",\\"stage\\":\\"test\\",\\"completion\\":\\"exact diagnostic marker\\",\\"rationale\\":\\"verify default refusal\\"}");calls.WorkerTasksStart.Invoke(session,"chief",1,"start","task",agent,"{\\"chunks\\":[\\"validated-result\\"]}");for(int i=0;i<1000;i++){var status=System.Text.Json.Nodes.JsonNode.Parse(calls.WorkerTasksPump.Invoke(session,"task"))!["status"]!.GetValue<string>();if(status=="awaiting-verification")break;System.Threading.Thread.Sleep(5);}bool denied=false;try{calls.WorkerTasksFinish.Invoke(session,"chief",1,"finish","task","marker-exact-check-passed");}catch(InvalidOperationException){denied=true;}if(!denied||System.Text.Json.Nodes.JsonNode.Parse(calls.WorkerTasksInspect.Invoke(session,"task"))!["status"]!.GetValue<string>()!="awaiting-verification")throw new Exception("default verification must refuse task completion");Console.WriteLine("PASS default completion policy refuses model-only task completion");return 0;}finally{calls.WorkerTasksClose.Invoke(session);calls.AgentClose.Invoke(agent);calls.HelperClose.Invoke(helpers);}
''')
c=build();r=subprocess.run(c['run'],env=env,capture_output=True,text=True,timeout=20);assert r.returncode==0,r.stderr;print(r.stdout,end='')
