using System.Security.Cryptography;
using System.Text;
using System.Text.Json.Nodes;
using Confectory.Core;
public static class ProjectionArtifacts
{
 static string Hash(byte[] bytes)=>Convert.ToHexString(SHA256.HashData(bytes)).ToLowerInvariant();
 static string HashText(string text)=>Hash(Encoding.UTF8.GetBytes(text));
 static FileStream Lock(string root){Directory.CreateDirectory(root);var timer=System.Diagnostics.Stopwatch.StartNew();while(true){try{return new FileStream(Path.Combine(root,"store.lock"),FileMode.OpenOrCreate,FileAccess.ReadWrite,FileShare.None);}catch(IOException){if(timer.ElapsedMilliseconds>5000)throw new IOException("Projection store busy; retry explicitly");Thread.Sleep(10);}}}
 public static JsonNode Execute(string operation,JsonNode request)
 {
  string project=Path.GetFullPath(request["project"]!.GetValue<string>());var statistics=new BuildStatistics();var registry=new Registry(project,new Documents(Path.Combine(Path.GetDirectoryName(project)!,".confectory","projection-documents"),statistics),statistics);
  if(operation=="projectionQueue"){
   string queueRoot=Path.Combine(Path.GetDirectoryName(project)!,".confectory","editor-projections");using var queueLock=Lock(queueRoot);string queuePath=Path.Combine(queueRoot,"maintenance.json");var queue=File.Exists(queuePath)?JsonNode.Parse(File.ReadAllText(queuePath))!.AsObject():new JsonObject{["schema"]=1,["owners"]=new JsonObject()};string queueOwner=HashText(request["participant"]!.ToString()+"\n"+request["context"]!.ToString());var owners=queue["owners"]!.AsObject();var entries=owners[queueOwner] as JsonObject??new JsonObject();string action=request["action"]!.GetValue<string>();if(action=="list")return new JsonArray(entries.Select(x=>x.Value!.DeepClone()).ToArray());if(owners.Count>=64&&owners[queueOwner] is null)throw new InvalidOperationException("Maintenance owner capacity reached");bool changed=false;
   if(action=="notify"){var item=request["request"]!.DeepClone().AsObject();string f=item["function"]!.GetValue<string>(),i=item["implementation"]!.GetValue<string>(),t=item["bodyID"]!.GetValue<string>();if(!f.Contains("::",StringComparison.Ordinal)||!t.StartsWith(i+"/body:",StringComparison.Ordinal))throw new ArgumentException("Qualified maintenance identity required");string queueKey=HashText(f+"\n"+i+"\n"+t);string origin=item["origin"]!.GetValue<string>(),kind=item["changeKind"]!.GetValue<string>();if(origin=="human"&&kind=="functional"){if(entries.Count>=256&&entries[queueKey] is null)throw new InvalidOperationException("Maintenance capacity reached");item["requestID"]=HashText(item.ToJsonString());entries[queueKey]=item;changed=true;}else if(origin=="ai")changed=entries.Remove(queueKey);}
   else if(action=="ack"){string id=request["requestID"]!.GetValue<string>();foreach(var entry in entries.ToArray())if(entry.Value!["requestID"]!.ToString()==id){entries.Remove(entry.Key);changed=true;}}
   else throw new ArgumentException("Unknown maintenance action");if(changed){owners[queueOwner]=entries;string temporary=queuePath+"."+Guid.NewGuid().ToString("N")+".tmp";try{File.WriteAllText(temporary,queue.ToJsonString(),new UTF8Encoding(false));File.Move(temporary,queuePath,true);}finally{if(File.Exists(temporary))File.Delete(temporary);}}return new JsonObject{["changed"]=changed};
  }
  if(operation=="editorDescribe"){var element=registry.Effective(request["element"]!.GetValue<string>());var result=AlgorithmProjectionOperations.Editor(element);result["version"]=Hash(File.ReadAllBytes(element.Loc.File));var origins=new JsonObject();foreach(var value in element.Values.Where(x=>x.Key.StartsWith("editor",StringComparison.Ordinal))){string origin=value.Value.Origin;var schema=registry.Get(origin);origins[value.Key]=new JsonObject{["schema"]=origin,["revision"]=Hash(File.ReadAllBytes(schema.Loc.File))};}result["schemaOrigins"]=origins;return result;}
  if(operation=="projectionAffected"){var selected=request["changedIDs"]!.AsArray().Select(x=>x!.ToString()).ToHashSet(StringComparer.Ordinal);if(selected.Count>256)throw new ArgumentException("Bounded changed IDs required");string directory=Path.Combine(Path.GetDirectoryName(project)!,".confectory","editor-projections");var found=new JsonArray();var seen=new HashSet<string>(StringComparer.Ordinal);var known=new HashSet<string>(StringComparer.Ordinal);if(Directory.Exists(directory))foreach(string file in Directory.EnumerateFiles(directory,"*.json")){if(file.EndsWith(".history.json",StringComparison.Ordinal)||Path.GetFileName(file)=="maintenance.json")continue;var record=JsonNode.Parse(File.ReadAllText(file))!;if(record["dependencies"] is not JsonArray dependencies||!dependencies.Any(id=>selected.Contains(id!.ToString())))continue;foreach(var dependency in dependencies)known.Add(dependency!.ToString());string affectedKey=record["function"]+"|"+record["provider"]+"|"+record["target"];if(seen.Add(affectedKey))found.Add(new JsonObject{["function"]=record["function"]!.DeepClone(),["implementation"]=record["provider"]!.DeepClone(),["bodyID"]=record["target"]!.DeepClone()});}return new JsonObject{["affected"]=found,["unknownIDs"]=new JsonArray(selected.Where(id=>!known.Contains(id)).Select(id=>(JsonNode?)JsonValue.Create(id)).ToArray()),["scope"]="stored projection dependency index only; no whole-project source scan"};}
  if(operation=="projectionVersions"){string f=request["function"]!.ToString(),i=request["implementation"]!.ToString(),t=request["target"]!.ToString();string stem=HashText(f+"\n"+i+"\n"+t),directory=Path.Combine(Path.GetDirectoryName(project)!,".confectory","editor-projections"),draftOwner=HashText(request["participant"]!.ToString()+"\n"+request["context"]!.ToString());using var versionLock=Lock(directory);long Version(string owner){string file=Path.Combine(directory,stem+"."+owner+".json");return File.Exists(file)?JsonNode.Parse(File.ReadAllText(file))!["version"]!.GetValue<long>():0;}return new JsonObject{["confirmed"]=Version("source"),["draft"]=Version(draftOwner)};}
  if(operation=="projectionList"){string selected=request["function"]!.GetValue<string>();registry.Get(selected,"function");string directory=Path.Combine(Path.GetDirectoryName(project)!,".confectory","editor-projections");var entries=new JsonArray();if(Directory.Exists(directory))foreach(string file in Directory.EnumerateFiles(directory,"*.json").OrderBy(x=>x,StringComparer.Ordinal)){if(Path.GetFileName(file)=="maintenance.json"||file.EndsWith(".history.json",StringComparison.Ordinal))continue;var record=JsonNode.Parse(File.ReadAllText(file))!;if(record["channel"]?.ToString()!=(request["channel"]?.ToString()??"confirmed"))continue;if(record["channel"]?.ToString()=="draft"&&record["owner"]?.ToString()!=HashText(request["participant"]!.ToString()+"\n"+request["context"]!.ToString()))continue;if(record["function"]?.ToString()==selected)entries.Add(new JsonObject{["function"]=selected,["implementation"]=record["provider"]!.DeepClone(),["target"]=record["target"]!.DeepClone(),["version"]=record["version"]!.DeepClone()});}return entries;}
  string function=request["function"]!.GetValue<string>(),implementation=request["implementation"]!.GetValue<string>(),target=request["target"]!.GetValue<string>();if(!function.Contains("::",StringComparison.Ordinal)||!implementation.Contains("::",StringComparison.Ordinal)||!target.StartsWith(implementation+"/body:",StringComparison.Ordinal))throw new ArgumentException("Qualified function/implementation/body-target IDs required");
  var contract=registry.Effective(function);var provider=registry.Effective(implementation);if(contract.Kind!="function"||provider.Kind!="implementation"||provider.Function!=function||!contract.Signature!.Matches(provider.Signature))throw new ArgumentException("Public function/provider identity mismatch");string variant=target[(implementation.Length+6)..];if(!provider.Bodies.TryGetValue(variant,out var body))throw new ArgumentException("Exact body variant missing; no silent common fallback");
  var paths=new Dictionary<string,string>{{"contract",contract.Loc.File},{"implementation",provider.Loc.File},{"body",PackPaths.Owned(Path.GetDirectoryName(registry.Paths[body.Origin.Split("::",StringSplitOptions.None)[0]])!,body.Path,body.Loc)}};
  foreach(string origin in contract.Values.Values.Select(v=>v.Origin).Where(origin=>origin!=function).Distinct(StringComparer.Ordinal))paths["schema:"+origin]=registry.Get(origin).Loc.File;
  var raw=new JsonObject();var content=new JsonObject();foreach(var item in paths){byte[] bytes=File.ReadAllBytes(item.Value);raw[item.Key]=Hash(bytes);content[item.Key]=HashText(File.ReadAllText(item.Value));}
  string root=Path.Combine(Path.GetDirectoryName(project)!,".confectory","editor-projections"),key=HashText(function+"\n"+implementation+"\n"+target);string channel=request["channel"]?.ToString()??"confirmed";if(channel!="confirmed"&&channel!="draft")throw new ArgumentException("Explicit confirmed/draft channel required");string owner=channel=="draft"?HashText(request["participant"]!.ToString()+"\n"+request["context"]!.ToString()):"source";string path=Path.Combine(root,key+"."+owner+".json");using var held=Lock(root);foreach(var item in paths){raw[item.Key]=Hash(File.ReadAllBytes(item.Value));content[item.Key]=HashText(File.ReadAllText(item.Value));}JsonObject? previous=File.Exists(path)?JsonNode.Parse(File.ReadAllText(path))!.AsObject():null;
  void Trace(){string? trace=Environment.GetEnvironmentVariable("CONFECTORY_PROJECTION_TRACE");if(trace is not null)File.AppendAllText(trace,new JsonObject{["operation"]=operation,["registryReads"]=new JsonArray(statistics.ReadDocuments.Select(p=>(JsonNode?)JsonValue.Create(p)).ToArray()),["serviceDigestReads"]=new JsonArray(paths.Values.Select(p=>(JsonNode?)JsonValue.Create(p)).ToArray()),["artifact"]=path,["returnedRawSource"]=false}.ToJsonString()+"\n");}
  if(operation=="projectionPublish"){
   var artifact=request["artifact"]!.DeepClone().AsObject();var expected=request["sourceHashes"]!.AsObject();if(artifact["schema"]!.GetValue<int>()!=2||artifact["function"]!.ToString()!=function||artifact["provider"]!.ToString()!=implementation)throw new ArgumentException("Source-free projection schema/identity mismatch");
   string contractText=request["publicContract"]?.GetValue<string>()??File.ReadAllText(paths["contract"]);var publicContract=new Parser(contractText,"<public-contract>").ParseElement();if(HashText(contractText)!=artifact["contractHash"]!.ToString()||publicContract.Id!=function||publicContract.Description!=artifact["description"]!.ToString()||JsonNode.DeepEquals(System.Text.Json.JsonSerializer.SerializeToNode(publicContract.Signature),artifact["signature"])==false)throw new ArgumentException("Public description/signature is not bound to the declared contract revision");
   foreach(var item in raw.Where(item=>item.Key is "contract" or "implementation" or "body"))if(expected[item.Key]?.ToString()!=item.Value!.ToString()){Trace();return new JsonObject{["accepted"]=false,["reason"]="source-revision-raced",["previousVersion"]=previous?["version"]?.DeepClone()};}
   if(request["expectedVersion"] is not null&&request["expectedVersion"]!.GetValue<long>()!=(previous?["version"]?.GetValue<long>()??0)){Trace();return new JsonObject{["accepted"]=false,["reason"]="artifact-version-raced"};}
   if(!File.Exists(path)&&Directory.EnumerateFiles(root,"*.json").Count(f=>!f.EndsWith(".history.json",StringComparison.Ordinal)&&Path.GetFileName(f)!="maintenance.json")>=512)throw new InvalidOperationException("Projection capacity reached; explicit retention required");
   void CheckTree(JsonNode node){foreach(string property in node.AsObject().Select(x=>x.Key))if(property is not ("kind" or "label" or "line" or "children" or "callee" or "certainty" or "nodeID"))throw new ArgumentException("Projection node exposes unsupported information");string kind=node["kind"]!.GetValue<string>();if(!new[]{"block","branch","else","finally","switch","case","lambda","local-function","loop","try","catch","throw","return","await","call","assignment","declaration","statement","unavailable"}.Contains(kind,StringComparer.Ordinal))throw new ArgumentException("Unknown syntax node kind");node["certainty"]="syntax-observed; behavior unverified";string? callee=node["callee"]?.GetValue<string>();if(callee is not null&&!provider.Imports.Values.Any(i=>i.Id==callee))throw new ArgumentException("Unrecognized public call identity");node["label"]=callee is null?kind:"public call "+callee;foreach(var child in node["children"]!.AsArray())CheckTree(child!);}
   CheckTree(artifact["tree"]!);var allowed=new HashSet<string>{"schema","function","provider","description","signature","imports","bodyHash","contractHash","implementationHash","status","validation","diagnostics","tree","claims","unknowns","effects","editor","bodyRevision","contractRevision","implementationRevision","bodyID","implementation","analysisMetrics"};foreach(string property in artifact.Select(x=>x.Key))if(!allowed.Contains(property))throw new ArgumentException("Unknown public artifact property");
   bool sourceCurrent=content["body"]!.ToString()==artifact["bodyHash"]!.ToString()&&content["contract"]!.ToString()==artifact["contractHash"]!.ToString()&&content["implementation"]!.ToString()==artifact["implementationHash"]!.ToString();if(channel=="confirmed"&&!sourceCurrent)return new JsonObject{["accepted"]=false,["reason"]="draft-cannot-publish-to-confirmed-channel"};artifact["editor"]=AlgorithmProjectionOperations.Editor(contract);artifact["target"]=target;artifact["channel"]=channel;artifact["owner"]=owner;artifact["sourceHashes"]=raw;artifact["dependencies"]=new JsonArray(function,implementation,target);foreach(string origin in contract.Values.Values.Select(v=>v.Origin).Distinct(StringComparer.Ordinal))if(!artifact["dependencies"]!.AsArray().Any(id=>id!.ToString()==origin))artifact["dependencies"]!.AsArray().Add(origin);artifact["claims"]=new JsonObject{["level"]="syntactic-outline",["semanticReview"]="not-performed",["behaviorValidated"]=false};artifact["version"]=(previous?["version"]?.GetValue<long>()??0)+1;artifact["project"]=registry.Project.Namespace;artifact["semanticReview"]="not-performed";string text=artifact.ToJsonString();if(Encoding.UTF8.GetByteCount(text)>8388608)throw new ArgumentException("Projection artifact capacity exceeded");string temporary=path+"."+Guid.NewGuid().ToString("N")+".tmp";try{File.WriteAllText(temporary,text,new UTF8Encoding(false));string historyPath=path+".history.json";var history=File.Exists(historyPath)?JsonNode.Parse(File.ReadAllText(historyPath))!.AsArray():new JsonArray();history.Add(artifact.DeepClone());while(history.Count>8)history.RemoveAt(0);string historyTemporary=historyPath+"."+Guid.NewGuid().ToString("N")+".tmp";try{File.WriteAllText(historyTemporary,history.ToJsonString(),new UTF8Encoding(false));File.Move(historyTemporary,historyPath,true);}finally{if(File.Exists(historyTemporary))File.Delete(historyTemporary);}File.Move(temporary,path,true);}finally{if(File.Exists(temporary))File.Delete(temporary);}Trace();return new JsonObject{["accepted"]=true,["version"]=artifact["version"]!.DeepClone()};
  }
  if(operation!="projectionQuery")throw new ArgumentException("Unknown projection operation");Trace();if(previous is null)return new JsonObject{["status"]="missing",["freshness"]="missing",["function"]=function,["implementation"]=implementation,["target"]=target};
  bool schemasCurrent=raw.Where(item=>item.Key.StartsWith("schema:",StringComparison.Ordinal)).All(item=>previous["sourceHashes"]?[item.Key]?.ToString()==item.Value!.ToString());bool current=schemasCurrent&&content["body"]!.ToString()==previous["bodyHash"]!.ToString()&&content["contract"]!.ToString()==previous["contractHash"]!.ToString()&&content["implementation"]!.ToString()==previous["implementationHash"]!.ToString();bool baseline=raw.All(item=>previous["sourceHashes"]?[item.Key]?.ToString()==item.Value!.ToString());previous["freshness"]=current?"current-source":baseline?"draft-unconfirmed":"stale-source";previous["status"]=previous["diagnostics"]!.AsArray().Count>0?"invalid-syntax":current?"current-unreviewed":baseline?"draft-unconfirmed":"stale";previous["behaviorValidated"]=false;return previous;
 }
}
