using System.Security.Cryptography;
using System.Text;
using System.Text.Json.Nodes;
public static class ProjectionDelivery
{
 static string Hash(string value)=>Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(value))).ToLowerInvariant();
 static JsonObject Select(JsonNode artifact,JsonNode options)
 {
  int depth=options["depth"]?.GetValue<int>()??0,size=options["pageSize"]?.GetValue<int>()??16,offset=options["offset"]?.GetValue<int>()??0,budget=options["nodeLimit"]?.GetValue<int>()??64;if(depth<0||depth>8||size<1||size>64||offset<0||budget<1||budget>256)throw new ArgumentException("Projection depth/page/node limits invalid");
  string selection=options["nodeID"]?.GetValue<string>()??"root";JsonNode root=artifact["tree"]!,selected=root;bool found=selection=="root";var pending=new Stack<JsonNode>();pending.Push(root);while(!found&&pending.Count>0){var node=pending.Pop();if(node["nodeID"]!.ToString()==selection){selected=node;found=true;break;}foreach(var child in node["children"]!.AsArray())pending.Push(child!);}if(!found)return new JsonObject{["status"]="node-not-found",["requiresRefresh"]=true,["version"]=artifact["version"]!.DeepClone()};
  var nodes=new JsonArray();var queue=new Queue<(JsonNode Node,int Depth)>();queue.Enqueue((selected,0));while(queue.Count>0&&nodes.Count<budget){var next=queue.Dequeue();var children=next.Node["children"]!.AsArray();int first=next.Depth==0?offset:0;var identifiers=new JsonArray();foreach(var child in children.Skip(first).Take(size))identifiers.Add(child!["nodeID"]!.DeepClone());nodes.Add(new JsonObject{["nodeID"]=next.Node["nodeID"]!.DeepClone(),["kind"]=next.Node["kind"]!.DeepClone(),["label"]=next.Node["label"]!.DeepClone(),["line"]=next.Node["line"]!.DeepClone(),["callee"]=next.Node["callee"]?.DeepClone(),["childCount"]=children.Count,["childIDs"]=identifiers,["nextOffset"]=first+size<children.Count?first+size:null});if(next.Depth<depth)foreach(var child in children.Skip(first).Take(size))queue.Enqueue((child!,next.Depth+1));}
  string scope=artifact["function"]+"|"+artifact["provider"]+"|"+artifact["target"]+"|"+artifact["channel"]+"|"+artifact["owner"];var result=new JsonObject{["status"]=artifact["status"]!.DeepClone(),["freshness"]=artifact["freshness"]?.DeepClone(),["scope"]=scope,["version"]=artifact["version"]!.DeepClone(),["bodyHash"]=artifact["bodyHash"]!.DeepClone(),["contractHash"]=artifact["contractHash"]!.DeepClone(),["selection"]=selection,["rootID"]=root["nodeID"]!.DeepClone(),["nodes"]=nodes,["truncated"]=queue.Count>0||selected["children"]!.AsArray().Count>offset+size,["descriptionPreview"]=artifact["description"]!.ToString()[..Math.Min(1024,artifact["description"]!.ToString().Length)],["descriptionTruncated"]=artifact["description"]!.ToString().Length>1024,["semanticReview"]="not-performed",["analysisCost"]="full selected-function parse may be required; bounded delivery does not imply incremental analysis"};result["viewHash"]=Hash(result.ToJsonString());if(Encoding.UTF8.GetByteCount(result.ToJsonString())>32768)throw new ArgumentException("Bounded projection response too large; request fewer nodes");return result;
 }
 public static JsonNode Execute(string operation,JsonNode request)
 {
  var current=ProjectionArtifacts.Execute("projectionQuery",request);if(current["tree"] is null)return current;var options=request["options"]??request;long version=current["version"]!.GetValue<long>();if(operation=="projectionBrowse"){if(options["expectedVersion"] is not null&&options["expectedVersion"]!.GetValue<long>()!=version)return new JsonObject{["status"]="version-mismatch",["requiresRefresh"]=true,["currentVersion"]=version};return Select(current,options);}
  if(operation!="projectionDelta")throw new ArgumentException("Unknown projection delivery operation");long baseline=request["baseVersion"]!.GetValue<long>();var snapshot=Select(current,options);if(current["status"]!.ToString()=="stale"||current["freshness"]!.ToString()=="stale-source")return new JsonObject{["status"]="stale-source",["requiresRefresh"]=true,["snapshot"]=snapshot};if(request["newVersion"] is not null&&request["newVersion"]!.GetValue<long>()!=version)return new JsonObject{["status"]="new-version-mismatch",["requiresRefresh"]=true,["currentVersion"]=version};
  string key=Hash(request["function"]+"\n"+request["implementation"]+"\n"+request["target"]);string owner=current["owner"]!.ToString();string path=Path.Combine(Path.GetDirectoryName(Path.GetFullPath(request["project"]!.GetValue<string>()))!,".confectory","editor-projections",key+"."+owner+".json.history.json");JsonNode? prior=null;if(File.Exists(path))foreach(var artifact in JsonNode.Parse(File.ReadAllText(path))!.AsArray())if(artifact!["version"]!.GetValue<long>()==baseline)prior=artifact;if(prior is null||baseline>version)return new JsonObject{["status"]="baseline-missing",["requiresRefresh"]=true,["snapshot"]=snapshot};if((options["nodeID"]?.ToString()??"root")!="root"&&prior["bodyHash"]!.ToString()!=current["bodyHash"]!.ToString())return new JsonObject{["status"]="node-identity-retired",["requiresRefresh"]=true,["snapshot"]=Select(current,new JsonObject())};
  // Historical freshness is not claimed; reconstruct exactly the delivered base header for hashing.
  prior["status"]=request["baseStatus"]?.DeepClone()??JsonValue.Create("current-unreviewed");prior["freshness"]=request["baseFreshness"]?.DeepClone()??JsonValue.Create("current-source");var baseView=Select(prior,options);var delta=new JsonObject{["status"]="delta",["scope"]=snapshot["scope"]!.DeepClone(),["baseVersion"]=baseline,["newVersion"]=version,["baseViewHash"]=baseView["viewHash"]!.DeepClone(),["newViewHash"]=snapshot["viewHash"]!.DeepClone(),["operation"]="replace-bounded-selection",["snapshot"]=snapshot,["stableIdentity"]="node identity retained only while body content hash is unchanged; no semantic identity claim"};delta["deltaID"]=Hash(delta.ToJsonString());if(Encoding.UTF8.GetByteCount(delta.ToJsonString())>32768)throw new ArgumentException("Bounded delta response too large; request fewer nodes");return delta;
 }
}
